// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: game-events.proto

package gameevents

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WasteType int32

const (
	WasteType_PLASTIC_BOTTLE           WasteType = 0
	WasteType_PLASTIC_JUG              WasteType = 1
	WasteType_PLASTIC_DETERGENT_BOTTLE WasteType = 2
	WasteType_PAPER_NEWSPAPER          WasteType = 3
	WasteType_PAPER_BAG                WasteType = 4
	WasteType_GLASS_SODA_BOTTLE        WasteType = 5
	WasteType_GLASS_JAR                WasteType = 6
	WasteType_GLASS_BOTTLE             WasteType = 7
	WasteType_METAL_SMALL_CAN          WasteType = 8
	WasteType_METAL_CAN                WasteType = 9
	WasteType_METAL_SODA_CAN           WasteType = 10
	WasteType_POLYSTYRENE_CUP          WasteType = 11
	WasteType_PIZZA_BOX                WasteType = 12
	WasteType_MUG                      WasteType = 13
	WasteType_AEROSOL_CAN              WasteType = 14
)

// Enum value maps for WasteType.
var (
	WasteType_name = map[int32]string{
		0:  "PLASTIC_BOTTLE",
		1:  "PLASTIC_JUG",
		2:  "PLASTIC_DETERGENT_BOTTLE",
		3:  "PAPER_NEWSPAPER",
		4:  "PAPER_BAG",
		5:  "GLASS_SODA_BOTTLE",
		6:  "GLASS_JAR",
		7:  "GLASS_BOTTLE",
		8:  "METAL_SMALL_CAN",
		9:  "METAL_CAN",
		10: "METAL_SODA_CAN",
		11: "POLYSTYRENE_CUP",
		12: "PIZZA_BOX",
		13: "MUG",
		14: "AEROSOL_CAN",
	}
	WasteType_value = map[string]int32{
		"PLASTIC_BOTTLE":           0,
		"PLASTIC_JUG":              1,
		"PLASTIC_DETERGENT_BOTTLE": 2,
		"PAPER_NEWSPAPER":          3,
		"PAPER_BAG":                4,
		"GLASS_SODA_BOTTLE":        5,
		"GLASS_JAR":                6,
		"GLASS_BOTTLE":             7,
		"METAL_SMALL_CAN":          8,
		"METAL_CAN":                9,
		"METAL_SODA_CAN":           10,
		"POLYSTYRENE_CUP":          11,
		"PIZZA_BOX":                12,
		"MUG":                      13,
		"AEROSOL_CAN":              14,
	}
)

func (x WasteType) Enum() *WasteType {
	p := new(WasteType)
	*p = x
	return p
}

func (x WasteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WasteType) Descriptor() protoreflect.EnumDescriptor {
	return file_game_events_proto_enumTypes[0].Descriptor()
}

func (WasteType) Type() protoreflect.EnumType {
	return &file_game_events_proto_enumTypes[0]
}

func (x WasteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WasteType.Descriptor instead.
func (WasteType) EnumDescriptor() ([]byte, []int) {
	return file_game_events_proto_rawDescGZIP(), []int{0}
}

type RoomGameDataReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Players      []*PlayerInRoomGameData `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	PlayersLimit int32                   `protobuf:"varint,3,opt,name=playersLimit,proto3" json:"playersLimit,omitempty"`
}

func (x *RoomGameDataReply) Reset() {
	*x = RoomGameDataReply{}
	mi := &file_game_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomGameDataReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGameDataReply) ProtoMessage() {}

func (x *RoomGameDataReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGameDataReply.ProtoReflect.Descriptor instead.
func (*RoomGameDataReply) Descriptor() ([]byte, []int) {
	return file_game_events_proto_rawDescGZIP(), []int{0}
}

func (x *RoomGameDataReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoomGameDataReply) GetPlayers() []*PlayerInRoomGameData {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *RoomGameDataReply) GetPlayersLimit() int32 {
	if x != nil {
		return x.PlayersLimit
	}
	return 0
}

type PlayerInRoomGameData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *PlayerInRoomGameData) Reset() {
	*x = PlayerInRoomGameData{}
	mi := &file_game_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInRoomGameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInRoomGameData) ProtoMessage() {}

func (x *PlayerInRoomGameData) ProtoReflect() protoreflect.Message {
	mi := &file_game_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInRoomGameData.ProtoReflect.Descriptor instead.
func (*PlayerInRoomGameData) Descriptor() ([]byte, []int) {
	return file_game_events_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerInRoomGameData) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type SubscriptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId       string `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	PlayerNumber int32  `protobuf:"varint,2,opt,name=playerNumber,proto3" json:"playerNumber,omitempty"`
}

func (x *SubscriptionRequest) Reset() {
	*x = SubscriptionRequest{}
	mi := &file_game_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionRequest) ProtoMessage() {}

func (x *SubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_game_events_proto_rawDescGZIP(), []int{2}
}

func (x *SubscriptionRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SubscriptionRequest) GetPlayerNumber() int32 {
	if x != nil {
		return x.PlayerNumber
	}
	return 0
}

type StartGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
}

func (x *StartGameRequest) Reset() {
	*x = StartGameRequest{}
	mi := &file_game_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameRequest) ProtoMessage() {}

func (x *StartGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameRequest.ProtoReflect.Descriptor instead.
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return file_game_events_proto_rawDescGZIP(), []int{3}
}

func (x *StartGameRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// Events
type Unspecified struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Unspecified) Reset() {
	*x = Unspecified{}
	mi := &file_game_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unspecified) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unspecified) ProtoMessage() {}

func (x *Unspecified) ProtoReflect() protoreflect.Message {
	mi := &file_game_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unspecified.ProtoReflect.Descriptor instead.
func (*Unspecified) Descriptor() ([]byte, []int) {
	return file_game_events_proto_rawDescGZIP(), []int{4}
}

type PlayerAdded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerNumber int32 `protobuf:"varint,1,opt,name=playerNumber,proto3" json:"playerNumber,omitempty"`
}

func (x *PlayerAdded) Reset() {
	*x = PlayerAdded{}
	mi := &file_game_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerAdded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerAdded) ProtoMessage() {}

func (x *PlayerAdded) ProtoReflect() protoreflect.Message {
	mi := &file_game_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerAdded.ProtoReflect.Descriptor instead.
func (*PlayerAdded) Descriptor() ([]byte, []int) {
	return file_game_events_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerAdded) GetPlayerNumber() int32 {
	if x != nil {
		return x.PlayerNumber
	}
	return 0
}

type PlayerRemoved struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerNumber int32 `protobuf:"varint,1,opt,name=playerNumber,proto3" json:"playerNumber,omitempty"`
}

func (x *PlayerRemoved) Reset() {
	*x = PlayerRemoved{}
	mi := &file_game_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerRemoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRemoved) ProtoMessage() {}

func (x *PlayerRemoved) ProtoReflect() protoreflect.Message {
	mi := &file_game_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRemoved.ProtoReflect.Descriptor instead.
func (*PlayerRemoved) Descriptor() ([]byte, []int) {
	return file_game_events_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerRemoved) GetPlayerNumber() int32 {
	if x != nil {
		return x.PlayerNumber
	}
	return 0
}

type GameStarted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GameStarted) Reset() {
	*x = GameStarted{}
	mi := &file_game_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStarted) ProtoMessage() {}

func (x *GameStarted) ProtoReflect() protoreflect.Message {
	mi := &file_game_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStarted.ProtoReflect.Descriptor instead.
func (*GameStarted) Descriptor() ([]byte, []int) {
	return file_game_events_proto_rawDescGZIP(), []int{7}
}

func (x *GameStarted) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WasteGenerated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Waste WasteType `protobuf:"varint,1,opt,name=waste,proto3,enum=ecoheroes.WasteType" json:"waste,omitempty"`
}

func (x *WasteGenerated) Reset() {
	*x = WasteGenerated{}
	mi := &file_game_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WasteGenerated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WasteGenerated) ProtoMessage() {}

func (x *WasteGenerated) ProtoReflect() protoreflect.Message {
	mi := &file_game_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WasteGenerated.ProtoReflect.Descriptor instead.
func (*WasteGenerated) Descriptor() ([]byte, []int) {
	return file_game_events_proto_rawDescGZIP(), []int{8}
}

func (x *WasteGenerated) GetWaste() WasteType {
	if x != nil {
		return x.Waste
	}
	return WasteType_PLASTIC_BOTTLE
}

type LifeLost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lives        int32 `protobuf:"varint,1,opt,name=lives,proto3" json:"lives,omitempty"`
	PlayerNumber int32 `protobuf:"varint,2,opt,name=playerNumber,proto3" json:"playerNumber,omitempty"`
}

func (x *LifeLost) Reset() {
	*x = LifeLost{}
	mi := &file_game_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifeLost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifeLost) ProtoMessage() {}

func (x *LifeLost) ProtoReflect() protoreflect.Message {
	mi := &file_game_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifeLost.ProtoReflect.Descriptor instead.
func (*LifeLost) Descriptor() ([]byte, []int) {
	return file_game_events_proto_rawDescGZIP(), []int{9}
}

func (x *LifeLost) GetLives() int32 {
	if x != nil {
		return x.Lives
	}
	return 0
}

func (x *LifeLost) GetPlayerNumber() int32 {
	if x != nil {
		return x.PlayerNumber
	}
	return 0
}

type SpeedIncreased struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Speed int32 `protobuf:"varint,1,opt,name=speed,proto3" json:"speed,omitempty"`
}

func (x *SpeedIncreased) Reset() {
	*x = SpeedIncreased{}
	mi := &file_game_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeedIncreased) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeedIncreased) ProtoMessage() {}

func (x *SpeedIncreased) ProtoReflect() protoreflect.Message {
	mi := &file_game_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeedIncreased.ProtoReflect.Descriptor instead.
func (*SpeedIncreased) Descriptor() ([]byte, []int) {
	return file_game_events_proto_rawDescGZIP(), []int{10}
}

func (x *SpeedIncreased) GetSpeed() int32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type GameEnded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WinnerNumber int32 `protobuf:"varint,1,opt,name=winnerNumber,proto3" json:"winnerNumber,omitempty"`
}

func (x *GameEnded) Reset() {
	*x = GameEnded{}
	mi := &file_game_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEnded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEnded) ProtoMessage() {}

func (x *GameEnded) ProtoReflect() protoreflect.Message {
	mi := &file_game_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEnded.ProtoReflect.Descriptor instead.
func (*GameEnded) Descriptor() ([]byte, []int) {
	return file_game_events_proto_rawDescGZIP(), []int{11}
}

func (x *GameEnded) GetWinnerNumber() int32 {
	if x != nil {
		return x.WinnerNumber
	}
	return 0
}

type ServerEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//
	//	*ServerEvent_UnspecifiedEvt
	//	*ServerEvent_PlayerAddedEvt
	//	*ServerEvent_PlayerRemovedEvt
	//	*ServerEvent_GameStartedEvt
	//	*ServerEvent_WasteGeneratedEvt
	//	*ServerEvent_LifeLostEvt
	//	*ServerEvent_SpeedIncreasedEvt
	//	*ServerEvent_GameEndedEvt
	Event isServerEvent_Event `protobuf_oneof:"Event"`
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_game_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_game_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_game_events_proto_rawDescGZIP(), []int{12}
}

func (m *ServerEvent) GetEvent() isServerEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *ServerEvent) GetUnspecifiedEvt() *Unspecified {
	if x, ok := x.GetEvent().(*ServerEvent_UnspecifiedEvt); ok {
		return x.UnspecifiedEvt
	}
	return nil
}

func (x *ServerEvent) GetPlayerAddedEvt() *PlayerAdded {
	if x, ok := x.GetEvent().(*ServerEvent_PlayerAddedEvt); ok {
		return x.PlayerAddedEvt
	}
	return nil
}

func (x *ServerEvent) GetPlayerRemovedEvt() *PlayerRemoved {
	if x, ok := x.GetEvent().(*ServerEvent_PlayerRemovedEvt); ok {
		return x.PlayerRemovedEvt
	}
	return nil
}

func (x *ServerEvent) GetGameStartedEvt() *GameStarted {
	if x, ok := x.GetEvent().(*ServerEvent_GameStartedEvt); ok {
		return x.GameStartedEvt
	}
	return nil
}

func (x *ServerEvent) GetWasteGeneratedEvt() *WasteGenerated {
	if x, ok := x.GetEvent().(*ServerEvent_WasteGeneratedEvt); ok {
		return x.WasteGeneratedEvt
	}
	return nil
}

func (x *ServerEvent) GetLifeLostEvt() *LifeLost {
	if x, ok := x.GetEvent().(*ServerEvent_LifeLostEvt); ok {
		return x.LifeLostEvt
	}
	return nil
}

func (x *ServerEvent) GetSpeedIncreasedEvt() *SpeedIncreased {
	if x, ok := x.GetEvent().(*ServerEvent_SpeedIncreasedEvt); ok {
		return x.SpeedIncreasedEvt
	}
	return nil
}

func (x *ServerEvent) GetGameEndedEvt() *GameEnded {
	if x, ok := x.GetEvent().(*ServerEvent_GameEndedEvt); ok {
		return x.GameEndedEvt
	}
	return nil
}

type isServerEvent_Event interface {
	isServerEvent_Event()
}

type ServerEvent_UnspecifiedEvt struct {
	UnspecifiedEvt *Unspecified `protobuf:"bytes,1,opt,name=unspecifiedEvt,proto3,oneof"`
}

type ServerEvent_PlayerAddedEvt struct {
	PlayerAddedEvt *PlayerAdded `protobuf:"bytes,2,opt,name=playerAddedEvt,proto3,oneof"`
}

type ServerEvent_PlayerRemovedEvt struct {
	PlayerRemovedEvt *PlayerRemoved `protobuf:"bytes,3,opt,name=playerRemovedEvt,proto3,oneof"`
}

type ServerEvent_GameStartedEvt struct {
	GameStartedEvt *GameStarted `protobuf:"bytes,4,opt,name=gameStartedEvt,proto3,oneof"`
}

type ServerEvent_WasteGeneratedEvt struct {
	WasteGeneratedEvt *WasteGenerated `protobuf:"bytes,5,opt,name=wasteGeneratedEvt,proto3,oneof"`
}

type ServerEvent_LifeLostEvt struct {
	LifeLostEvt *LifeLost `protobuf:"bytes,6,opt,name=lifeLostEvt,proto3,oneof"`
}

type ServerEvent_SpeedIncreasedEvt struct {
	SpeedIncreasedEvt *SpeedIncreased `protobuf:"bytes,7,opt,name=speedIncreasedEvt,proto3,oneof"`
}

type ServerEvent_GameEndedEvt struct {
	GameEndedEvt *GameEnded `protobuf:"bytes,8,opt,name=gameEndedEvt,proto3,oneof"`
}

func (*ServerEvent_UnspecifiedEvt) isServerEvent_Event() {}

func (*ServerEvent_PlayerAddedEvt) isServerEvent_Event() {}

func (*ServerEvent_PlayerRemovedEvt) isServerEvent_Event() {}

func (*ServerEvent_GameStartedEvt) isServerEvent_Event() {}

func (*ServerEvent_WasteGeneratedEvt) isServerEvent_Event() {}

func (*ServerEvent_LifeLostEvt) isServerEvent_Event() {}

func (*ServerEvent_SpeedIncreasedEvt) isServerEvent_Event() {}

func (*ServerEvent_GameEndedEvt) isServerEvent_Event() {}

var File_game_events_proto protoreflect.FileDescriptor

var file_game_events_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x61, 0x6d, 0x65, 0x2d, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x09, 0x65, 0x63, 0x6f, 0x68, 0x65, 0x72, 0x6f, 0x65, 0x73, 0x22, 0x82,
	0x01, 0x0a, 0x11, 0x52, 0x6f, 0x6f, 0x6d, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x39, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x65, 0x63, 0x6f, 0x68, 0x65, 0x72, 0x6f, 0x65,
	0x73, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x47, 0x61,
	0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12,
	0x22, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x22, 0x2e, 0x0a, 0x14, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x52,
	0x6f, 0x6f, 0x6d, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x22, 0x51, 0x0a, 0x13, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x2a, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x22, 0x0d, 0x0a, 0x0b, 0x55, 0x6e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65,
	0x64, 0x22, 0x31, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x64, 0x64, 0x65, 0x64,
	0x12, 0x22, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x22, 0x33, 0x0a, 0x0d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x27, 0x0a, 0x0b, 0x47, 0x61, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x3c, 0x0a, 0x0e, 0x57, 0x61, 0x73, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x05, 0x77, 0x61, 0x73, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x65, 0x63, 0x6f, 0x68, 0x65, 0x72, 0x6f, 0x65, 0x73, 0x2e,
	0x57, 0x61, 0x73, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x77, 0x61, 0x73, 0x74, 0x65,
	0x22, 0x44, 0x0a, 0x08, 0x4c, 0x69, 0x66, 0x65, 0x4c, 0x6f, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x69, 0x76, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x76,
	0x65, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x26, 0x0a, 0x0e, 0x53, 0x70, 0x65, 0x65, 0x64, 0x49,
	0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x22, 0x2f,
	0x0a, 0x09, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x65, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x77,
	0x69, 0x6e, 0x6e, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0c, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22,
	0xaf, 0x04, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x40, 0x0a, 0x0e, 0x75, 0x6e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x64, 0x45, 0x76,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x65, 0x63, 0x6f, 0x68, 0x65, 0x72,
	0x6f, 0x65, 0x73, 0x2e, 0x55, 0x6e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x64, 0x48,
	0x00, 0x52, 0x0e, 0x75, 0x6e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x64, 0x45, 0x76,
	0x74, 0x12, 0x40, 0x0a, 0x0e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x64, 0x64, 0x65, 0x64,
	0x45, 0x76, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x65, 0x63, 0x6f, 0x68,
	0x65, 0x72, 0x6f, 0x65, 0x73, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x64, 0x64, 0x65,
	0x64, 0x48, 0x00, 0x52, 0x0e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x64, 0x64, 0x65, 0x64,
	0x45, 0x76, 0x74, 0x12, 0x46, 0x0a, 0x10, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x64, 0x45, 0x76, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x65, 0x63, 0x6f, 0x68, 0x65, 0x72, 0x6f, 0x65, 0x73, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x48, 0x00, 0x52, 0x10, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x45, 0x76, 0x74, 0x12, 0x40, 0x0a, 0x0e, 0x67,
	0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x45, 0x76, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x65, 0x63, 0x6f, 0x68, 0x65, 0x72, 0x6f, 0x65, 0x73, 0x2e,
	0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0e, 0x67,
	0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x45, 0x76, 0x74, 0x12, 0x49, 0x0a,
	0x11, 0x77, 0x61, 0x73, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x45,
	0x76, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x65, 0x63, 0x6f, 0x68, 0x65,
	0x72, 0x6f, 0x65, 0x73, 0x2e, 0x57, 0x61, 0x73, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x11, 0x77, 0x61, 0x73, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x64, 0x45, 0x76, 0x74, 0x12, 0x37, 0x0a, 0x0b, 0x6c, 0x69, 0x66, 0x65,
	0x4c, 0x6f, 0x73, 0x74, 0x45, 0x76, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x65, 0x63, 0x6f, 0x68, 0x65, 0x72, 0x6f, 0x65, 0x73, 0x2e, 0x4c, 0x69, 0x66, 0x65, 0x4c, 0x6f,
	0x73, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x6c, 0x69, 0x66, 0x65, 0x4c, 0x6f, 0x73, 0x74, 0x45, 0x76,
	0x74, 0x12, 0x49, 0x0a, 0x11, 0x73, 0x70, 0x65, 0x65, 0x64, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x61,
	0x73, 0x65, 0x64, 0x45, 0x76, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x65,
	0x63, 0x6f, 0x68, 0x65, 0x72, 0x6f, 0x65, 0x73, 0x2e, 0x53, 0x70, 0x65, 0x65, 0x64, 0x49, 0x6e,
	0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x64, 0x48, 0x00, 0x52, 0x11, 0x73, 0x70, 0x65, 0x65, 0x64,
	0x49, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x64, 0x45, 0x76, 0x74, 0x12, 0x3a, 0x0a, 0x0c,
	0x67, 0x61, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x65, 0x64, 0x45, 0x76, 0x74, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x65, 0x63, 0x6f, 0x68, 0x65, 0x72, 0x6f, 0x65, 0x73, 0x2e, 0x47,
	0x61, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0c, 0x67, 0x61, 0x6d, 0x65,
	0x45, 0x6e, 0x64, 0x65, 0x64, 0x45, 0x76, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x2a, 0xa0, 0x02, 0x0a, 0x09, 0x57, 0x61, 0x73, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x12, 0x0a, 0x0e, 0x50, 0x4c, 0x41, 0x53, 0x54, 0x49, 0x43, 0x5f, 0x42, 0x4f, 0x54, 0x54, 0x4c,
	0x45, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x4c, 0x41, 0x53, 0x54, 0x49, 0x43, 0x5f, 0x4a,
	0x55, 0x47, 0x10, 0x01, 0x12, 0x1c, 0x0a, 0x18, 0x50, 0x4c, 0x41, 0x53, 0x54, 0x49, 0x43, 0x5f,
	0x44, 0x45, 0x54, 0x45, 0x52, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x42, 0x4f, 0x54, 0x54, 0x4c, 0x45,
	0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x41, 0x50, 0x45, 0x52, 0x5f, 0x4e, 0x45, 0x57, 0x53,
	0x50, 0x41, 0x50, 0x45, 0x52, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x41, 0x50, 0x45, 0x52,
	0x5f, 0x42, 0x41, 0x47, 0x10, 0x04, 0x12, 0x15, 0x0a, 0x11, 0x47, 0x4c, 0x41, 0x53, 0x53, 0x5f,
	0x53, 0x4f, 0x44, 0x41, 0x5f, 0x42, 0x4f, 0x54, 0x54, 0x4c, 0x45, 0x10, 0x05, 0x12, 0x0d, 0x0a,
	0x09, 0x47, 0x4c, 0x41, 0x53, 0x53, 0x5f, 0x4a, 0x41, 0x52, 0x10, 0x06, 0x12, 0x10, 0x0a, 0x0c,
	0x47, 0x4c, 0x41, 0x53, 0x53, 0x5f, 0x42, 0x4f, 0x54, 0x54, 0x4c, 0x45, 0x10, 0x07, 0x12, 0x13,
	0x0a, 0x0f, 0x4d, 0x45, 0x54, 0x41, 0x4c, 0x5f, 0x53, 0x4d, 0x41, 0x4c, 0x4c, 0x5f, 0x43, 0x41,
	0x4e, 0x10, 0x08, 0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x45, 0x54, 0x41, 0x4c, 0x5f, 0x43, 0x41, 0x4e,
	0x10, 0x09, 0x12, 0x12, 0x0a, 0x0e, 0x4d, 0x45, 0x54, 0x41, 0x4c, 0x5f, 0x53, 0x4f, 0x44, 0x41,
	0x5f, 0x43, 0x41, 0x4e, 0x10, 0x0a, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x4f, 0x4c, 0x59, 0x53, 0x54,
	0x59, 0x52, 0x45, 0x4e, 0x45, 0x5f, 0x43, 0x55, 0x50, 0x10, 0x0b, 0x12, 0x0d, 0x0a, 0x09, 0x50,
	0x49, 0x5a, 0x5a, 0x41, 0x5f, 0x42, 0x4f, 0x58, 0x10, 0x0c, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x55,
	0x47, 0x10, 0x0d, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x45, 0x52, 0x4f, 0x53, 0x4f, 0x4c, 0x5f, 0x43,
	0x41, 0x4e, 0x10, 0x0e, 0x32, 0x9b, 0x01, 0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x12, 0x45, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x12, 0x1e, 0x2e, 0x65, 0x63, 0x6f, 0x68, 0x65, 0x72, 0x6f, 0x65, 0x73, 0x2e, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x65, 0x63, 0x6f, 0x68, 0x65, 0x72, 0x6f, 0x65, 0x73, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x30, 0x01, 0x12, 0x46, 0x0a, 0x09, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x2e, 0x65, 0x63, 0x6f, 0x68, 0x65, 0x72,
	0x6f, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x65, 0x63, 0x6f, 0x68, 0x65, 0x72, 0x6f, 0x65, 0x73,
	0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x42, 0x4a, 0x0a, 0x27, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x65, 0x63, 0x6f, 0x5f, 0x68, 0x65, 0x72, 0x6f, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x0f, 0x47,
	0x61, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x0c, 0x2e, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_events_proto_rawDescOnce sync.Once
	file_game_events_proto_rawDescData = file_game_events_proto_rawDesc
)

func file_game_events_proto_rawDescGZIP() []byte {
	file_game_events_proto_rawDescOnce.Do(func() {
		file_game_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_events_proto_rawDescData)
	})
	return file_game_events_proto_rawDescData
}

var file_game_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_game_events_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_game_events_proto_goTypes = []any{
	(WasteType)(0),               // 0: ecoheroes.WasteType
	(*RoomGameDataReply)(nil),    // 1: ecoheroes.RoomGameDataReply
	(*PlayerInRoomGameData)(nil), // 2: ecoheroes.PlayerInRoomGameData
	(*SubscriptionRequest)(nil),  // 3: ecoheroes.SubscriptionRequest
	(*StartGameRequest)(nil),     // 4: ecoheroes.StartGameRequest
	(*Unspecified)(nil),          // 5: ecoheroes.Unspecified
	(*PlayerAdded)(nil),          // 6: ecoheroes.PlayerAdded
	(*PlayerRemoved)(nil),        // 7: ecoheroes.PlayerRemoved
	(*GameStarted)(nil),          // 8: ecoheroes.GameStarted
	(*WasteGenerated)(nil),       // 9: ecoheroes.WasteGenerated
	(*LifeLost)(nil),             // 10: ecoheroes.LifeLost
	(*SpeedIncreased)(nil),       // 11: ecoheroes.SpeedIncreased
	(*GameEnded)(nil),            // 12: ecoheroes.GameEnded
	(*ServerEvent)(nil),          // 13: ecoheroes.ServerEvent
}
var file_game_events_proto_depIdxs = []int32{
	2,  // 0: ecoheroes.RoomGameDataReply.players:type_name -> ecoheroes.PlayerInRoomGameData
	0,  // 1: ecoheroes.WasteGenerated.waste:type_name -> ecoheroes.WasteType
	5,  // 2: ecoheroes.ServerEvent.unspecifiedEvt:type_name -> ecoheroes.Unspecified
	6,  // 3: ecoheroes.ServerEvent.playerAddedEvt:type_name -> ecoheroes.PlayerAdded
	7,  // 4: ecoheroes.ServerEvent.playerRemovedEvt:type_name -> ecoheroes.PlayerRemoved
	8,  // 5: ecoheroes.ServerEvent.gameStartedEvt:type_name -> ecoheroes.GameStarted
	9,  // 6: ecoheroes.ServerEvent.wasteGeneratedEvt:type_name -> ecoheroes.WasteGenerated
	10, // 7: ecoheroes.ServerEvent.lifeLostEvt:type_name -> ecoheroes.LifeLost
	11, // 8: ecoheroes.ServerEvent.speedIncreasedEvt:type_name -> ecoheroes.SpeedIncreased
	12, // 9: ecoheroes.ServerEvent.gameEndedEvt:type_name -> ecoheroes.GameEnded
	3,  // 10: ecoheroes.GameEvents.subscribe:input_type -> ecoheroes.SubscriptionRequest
	4,  // 11: ecoheroes.GameEvents.startGame:input_type -> ecoheroes.StartGameRequest
	13, // 12: ecoheroes.GameEvents.subscribe:output_type -> ecoheroes.ServerEvent
	1,  // 13: ecoheroes.GameEvents.startGame:output_type -> ecoheroes.RoomGameDataReply
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_game_events_proto_init() }
func file_game_events_proto_init() {
	if File_game_events_proto != nil {
		return
	}
	file_game_events_proto_msgTypes[12].OneofWrappers = []any{
		(*ServerEvent_UnspecifiedEvt)(nil),
		(*ServerEvent_PlayerAddedEvt)(nil),
		(*ServerEvent_PlayerRemovedEvt)(nil),
		(*ServerEvent_GameStartedEvt)(nil),
		(*ServerEvent_WasteGeneratedEvt)(nil),
		(*ServerEvent_LifeLostEvt)(nil),
		(*ServerEvent_SpeedIncreasedEvt)(nil),
		(*ServerEvent_GameEndedEvt)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_events_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_events_proto_goTypes,
		DependencyIndexes: file_game_events_proto_depIdxs,
		EnumInfos:         file_game_events_proto_enumTypes,
		MessageInfos:      file_game_events_proto_msgTypes,
	}.Build()
	File_game_events_proto = out.File
	file_game_events_proto_rawDesc = nil
	file_game_events_proto_goTypes = nil
	file_game_events_proto_depIdxs = nil
}
