// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rooms.proto
// Protobuf Java Version: 4.28.2

package com.github.eco_heroes.proto.rooms;

public interface PlayerInRoomDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ecoheroes.PlayerInRoomData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   * @return The number.
   */
  int getNumber();
}
