// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rooms.proto
// Protobuf Java Version: 4.28.3

package com.github.eco_heroes.proto.rooms;

/**
 * Protobuf type {@code ecoheroes.RoomsListReply}
 */
public final class RoomsListReply extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ecoheroes.RoomsListReply)
    RoomsListReplyOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      RoomsListReply.class.getName());
  }
  // Use RoomsListReply.newBuilder() to construct.
  private RoomsListReply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RoomsListReply() {
    rooms_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.eco_heroes.proto.rooms.RoomsProto.internal_static_ecoheroes_RoomsListReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.eco_heroes.proto.rooms.RoomsProto.internal_static_ecoheroes_RoomsListReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.eco_heroes.proto.rooms.RoomsListReply.class, com.github.eco_heroes.proto.rooms.RoomsListReply.Builder.class);
  }

  public static final int ROOMS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.github.eco_heroes.proto.rooms.RoomDataReply> rooms_;
  /**
   * <code>repeated .ecoheroes.RoomDataReply rooms = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.github.eco_heroes.proto.rooms.RoomDataReply> getRoomsList() {
    return rooms_;
  }
  /**
   * <code>repeated .ecoheroes.RoomDataReply rooms = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.github.eco_heroes.proto.rooms.RoomDataReplyOrBuilder> 
      getRoomsOrBuilderList() {
    return rooms_;
  }
  /**
   * <code>repeated .ecoheroes.RoomDataReply rooms = 1;</code>
   */
  @java.lang.Override
  public int getRoomsCount() {
    return rooms_.size();
  }
  /**
   * <code>repeated .ecoheroes.RoomDataReply rooms = 1;</code>
   */
  @java.lang.Override
  public com.github.eco_heroes.proto.rooms.RoomDataReply getRooms(int index) {
    return rooms_.get(index);
  }
  /**
   * <code>repeated .ecoheroes.RoomDataReply rooms = 1;</code>
   */
  @java.lang.Override
  public com.github.eco_heroes.proto.rooms.RoomDataReplyOrBuilder getRoomsOrBuilder(
      int index) {
    return rooms_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < rooms_.size(); i++) {
      output.writeMessage(1, rooms_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < rooms_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, rooms_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.eco_heroes.proto.rooms.RoomsListReply)) {
      return super.equals(obj);
    }
    com.github.eco_heroes.proto.rooms.RoomsListReply other = (com.github.eco_heroes.proto.rooms.RoomsListReply) obj;

    if (!getRoomsList()
        .equals(other.getRoomsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRoomsCount() > 0) {
      hash = (37 * hash) + ROOMS_FIELD_NUMBER;
      hash = (53 * hash) + getRoomsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.eco_heroes.proto.rooms.RoomsListReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.eco_heroes.proto.rooms.RoomsListReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.eco_heroes.proto.rooms.RoomsListReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.eco_heroes.proto.rooms.RoomsListReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.eco_heroes.proto.rooms.RoomsListReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.eco_heroes.proto.rooms.RoomsListReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.eco_heroes.proto.rooms.RoomsListReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.eco_heroes.proto.rooms.RoomsListReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.github.eco_heroes.proto.rooms.RoomsListReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.github.eco_heroes.proto.rooms.RoomsListReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.eco_heroes.proto.rooms.RoomsListReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.eco_heroes.proto.rooms.RoomsListReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.eco_heroes.proto.rooms.RoomsListReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ecoheroes.RoomsListReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ecoheroes.RoomsListReply)
      com.github.eco_heroes.proto.rooms.RoomsListReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.eco_heroes.proto.rooms.RoomsProto.internal_static_ecoheroes_RoomsListReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.eco_heroes.proto.rooms.RoomsProto.internal_static_ecoheroes_RoomsListReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.eco_heroes.proto.rooms.RoomsListReply.class, com.github.eco_heroes.proto.rooms.RoomsListReply.Builder.class);
    }

    // Construct using com.github.eco_heroes.proto.rooms.RoomsListReply.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (roomsBuilder_ == null) {
        rooms_ = java.util.Collections.emptyList();
      } else {
        rooms_ = null;
        roomsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.eco_heroes.proto.rooms.RoomsProto.internal_static_ecoheroes_RoomsListReply_descriptor;
    }

    @java.lang.Override
    public com.github.eco_heroes.proto.rooms.RoomsListReply getDefaultInstanceForType() {
      return com.github.eco_heroes.proto.rooms.RoomsListReply.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.eco_heroes.proto.rooms.RoomsListReply build() {
      com.github.eco_heroes.proto.rooms.RoomsListReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.eco_heroes.proto.rooms.RoomsListReply buildPartial() {
      com.github.eco_heroes.proto.rooms.RoomsListReply result = new com.github.eco_heroes.proto.rooms.RoomsListReply(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.github.eco_heroes.proto.rooms.RoomsListReply result) {
      if (roomsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          rooms_ = java.util.Collections.unmodifiableList(rooms_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.rooms_ = rooms_;
      } else {
        result.rooms_ = roomsBuilder_.build();
      }
    }

    private void buildPartial0(com.github.eco_heroes.proto.rooms.RoomsListReply result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.eco_heroes.proto.rooms.RoomsListReply) {
        return mergeFrom((com.github.eco_heroes.proto.rooms.RoomsListReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.eco_heroes.proto.rooms.RoomsListReply other) {
      if (other == com.github.eco_heroes.proto.rooms.RoomsListReply.getDefaultInstance()) return this;
      if (roomsBuilder_ == null) {
        if (!other.rooms_.isEmpty()) {
          if (rooms_.isEmpty()) {
            rooms_ = other.rooms_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRoomsIsMutable();
            rooms_.addAll(other.rooms_);
          }
          onChanged();
        }
      } else {
        if (!other.rooms_.isEmpty()) {
          if (roomsBuilder_.isEmpty()) {
            roomsBuilder_.dispose();
            roomsBuilder_ = null;
            rooms_ = other.rooms_;
            bitField0_ = (bitField0_ & ~0x00000001);
            roomsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getRoomsFieldBuilder() : null;
          } else {
            roomsBuilder_.addAllMessages(other.rooms_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.github.eco_heroes.proto.rooms.RoomDataReply m =
                  input.readMessage(
                      com.github.eco_heroes.proto.rooms.RoomDataReply.parser(),
                      extensionRegistry);
              if (roomsBuilder_ == null) {
                ensureRoomsIsMutable();
                rooms_.add(m);
              } else {
                roomsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.github.eco_heroes.proto.rooms.RoomDataReply> rooms_ =
      java.util.Collections.emptyList();
    private void ensureRoomsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        rooms_ = new java.util.ArrayList<com.github.eco_heroes.proto.rooms.RoomDataReply>(rooms_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.github.eco_heroes.proto.rooms.RoomDataReply, com.github.eco_heroes.proto.rooms.RoomDataReply.Builder, com.github.eco_heroes.proto.rooms.RoomDataReplyOrBuilder> roomsBuilder_;

    /**
     * <code>repeated .ecoheroes.RoomDataReply rooms = 1;</code>
     */
    public java.util.List<com.github.eco_heroes.proto.rooms.RoomDataReply> getRoomsList() {
      if (roomsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(rooms_);
      } else {
        return roomsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ecoheroes.RoomDataReply rooms = 1;</code>
     */
    public int getRoomsCount() {
      if (roomsBuilder_ == null) {
        return rooms_.size();
      } else {
        return roomsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ecoheroes.RoomDataReply rooms = 1;</code>
     */
    public com.github.eco_heroes.proto.rooms.RoomDataReply getRooms(int index) {
      if (roomsBuilder_ == null) {
        return rooms_.get(index);
      } else {
        return roomsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ecoheroes.RoomDataReply rooms = 1;</code>
     */
    public Builder setRooms(
        int index, com.github.eco_heroes.proto.rooms.RoomDataReply value) {
      if (roomsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRoomsIsMutable();
        rooms_.set(index, value);
        onChanged();
      } else {
        roomsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ecoheroes.RoomDataReply rooms = 1;</code>
     */
    public Builder setRooms(
        int index, com.github.eco_heroes.proto.rooms.RoomDataReply.Builder builderForValue) {
      if (roomsBuilder_ == null) {
        ensureRoomsIsMutable();
        rooms_.set(index, builderForValue.build());
        onChanged();
      } else {
        roomsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ecoheroes.RoomDataReply rooms = 1;</code>
     */
    public Builder addRooms(com.github.eco_heroes.proto.rooms.RoomDataReply value) {
      if (roomsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRoomsIsMutable();
        rooms_.add(value);
        onChanged();
      } else {
        roomsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ecoheroes.RoomDataReply rooms = 1;</code>
     */
    public Builder addRooms(
        int index, com.github.eco_heroes.proto.rooms.RoomDataReply value) {
      if (roomsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRoomsIsMutable();
        rooms_.add(index, value);
        onChanged();
      } else {
        roomsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ecoheroes.RoomDataReply rooms = 1;</code>
     */
    public Builder addRooms(
        com.github.eco_heroes.proto.rooms.RoomDataReply.Builder builderForValue) {
      if (roomsBuilder_ == null) {
        ensureRoomsIsMutable();
        rooms_.add(builderForValue.build());
        onChanged();
      } else {
        roomsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ecoheroes.RoomDataReply rooms = 1;</code>
     */
    public Builder addRooms(
        int index, com.github.eco_heroes.proto.rooms.RoomDataReply.Builder builderForValue) {
      if (roomsBuilder_ == null) {
        ensureRoomsIsMutable();
        rooms_.add(index, builderForValue.build());
        onChanged();
      } else {
        roomsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ecoheroes.RoomDataReply rooms = 1;</code>
     */
    public Builder addAllRooms(
        java.lang.Iterable<? extends com.github.eco_heroes.proto.rooms.RoomDataReply> values) {
      if (roomsBuilder_ == null) {
        ensureRoomsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rooms_);
        onChanged();
      } else {
        roomsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ecoheroes.RoomDataReply rooms = 1;</code>
     */
    public Builder clearRooms() {
      if (roomsBuilder_ == null) {
        rooms_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        roomsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ecoheroes.RoomDataReply rooms = 1;</code>
     */
    public Builder removeRooms(int index) {
      if (roomsBuilder_ == null) {
        ensureRoomsIsMutable();
        rooms_.remove(index);
        onChanged();
      } else {
        roomsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ecoheroes.RoomDataReply rooms = 1;</code>
     */
    public com.github.eco_heroes.proto.rooms.RoomDataReply.Builder getRoomsBuilder(
        int index) {
      return getRoomsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ecoheroes.RoomDataReply rooms = 1;</code>
     */
    public com.github.eco_heroes.proto.rooms.RoomDataReplyOrBuilder getRoomsOrBuilder(
        int index) {
      if (roomsBuilder_ == null) {
        return rooms_.get(index);  } else {
        return roomsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ecoheroes.RoomDataReply rooms = 1;</code>
     */
    public java.util.List<? extends com.github.eco_heroes.proto.rooms.RoomDataReplyOrBuilder> 
         getRoomsOrBuilderList() {
      if (roomsBuilder_ != null) {
        return roomsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(rooms_);
      }
    }
    /**
     * <code>repeated .ecoheroes.RoomDataReply rooms = 1;</code>
     */
    public com.github.eco_heroes.proto.rooms.RoomDataReply.Builder addRoomsBuilder() {
      return getRoomsFieldBuilder().addBuilder(
          com.github.eco_heroes.proto.rooms.RoomDataReply.getDefaultInstance());
    }
    /**
     * <code>repeated .ecoheroes.RoomDataReply rooms = 1;</code>
     */
    public com.github.eco_heroes.proto.rooms.RoomDataReply.Builder addRoomsBuilder(
        int index) {
      return getRoomsFieldBuilder().addBuilder(
          index, com.github.eco_heroes.proto.rooms.RoomDataReply.getDefaultInstance());
    }
    /**
     * <code>repeated .ecoheroes.RoomDataReply rooms = 1;</code>
     */
    public java.util.List<com.github.eco_heroes.proto.rooms.RoomDataReply.Builder> 
         getRoomsBuilderList() {
      return getRoomsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.github.eco_heroes.proto.rooms.RoomDataReply, com.github.eco_heroes.proto.rooms.RoomDataReply.Builder, com.github.eco_heroes.proto.rooms.RoomDataReplyOrBuilder> 
        getRoomsFieldBuilder() {
      if (roomsBuilder_ == null) {
        roomsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.github.eco_heroes.proto.rooms.RoomDataReply, com.github.eco_heroes.proto.rooms.RoomDataReply.Builder, com.github.eco_heroes.proto.rooms.RoomDataReplyOrBuilder>(
                rooms_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        rooms_ = null;
      }
      return roomsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:ecoheroes.RoomsListReply)
  }

  // @@protoc_insertion_point(class_scope:ecoheroes.RoomsListReply)
  private static final com.github.eco_heroes.proto.rooms.RoomsListReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.eco_heroes.proto.rooms.RoomsListReply();
  }

  public static com.github.eco_heroes.proto.rooms.RoomsListReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RoomsListReply>
      PARSER = new com.google.protobuf.AbstractParser<RoomsListReply>() {
    @java.lang.Override
    public RoomsListReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RoomsListReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RoomsListReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.eco_heroes.proto.rooms.RoomsListReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

