// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rooms.proto
// Protobuf Java Version: 4.28.2

package com.github.eco_heroes.proto.rooms;

public final class RoomsProto {
  private RoomsProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      RoomsProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ecoheroes_RoomDataReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ecoheroes_RoomDataReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ecoheroes_JoinRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ecoheroes_JoinRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ecoheroes_RoomsListReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ecoheroes_RoomsListReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ecoheroes_PlayerInRoomData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ecoheroes_PlayerInRoomData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013rooms.proto\022\tecoheroes\032\033google/protobu" +
      "f/empty.proto\"\210\001\n\rRoomDataReply\022\n\n\002id\030\001 " +
      "\001(\t\022,\n\007players\030\002 \003(\0132\033.ecoheroes.PlayerI" +
      "nRoomData\022\024\n\014playersLimit\030\003 \001(\005\022\'\n\002me\030\004 " +
      "\001(\0132\033.ecoheroes.PlayerInRoomData\"\035\n\013Join" +
      "Request\022\016\n\006roomId\030\001 \001(\t\"9\n\016RoomsListRepl" +
      "y\022\'\n\005rooms\030\001 \003(\0132\030.ecoheroes.RoomDataRep" +
      "ly\"\"\n\020PlayerInRoomData\022\016\n\006number\030\001 \001(\0052\300" +
      "\001\n\005Rooms\022A\n\rcreateAndJoin\022\026.google.proto" +
      "buf.Empty\032\030.ecoheroes.RoomDataReply\0228\n\004j" +
      "oin\022\026.ecoheroes.JoinRequest\032\030.ecoheroes." +
      "RoomDataReply\022:\n\005fetch\022\026.google.protobuf" +
      ".Empty\032\031.ecoheroes.RoomsListReplyB:\n!com" +
      ".github.eco_heroes.proto.roomsB\nRoomsPro" +
      "toP\001Z\007./roomsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_ecoheroes_RoomDataReply_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ecoheroes_RoomDataReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ecoheroes_RoomDataReply_descriptor,
        new java.lang.String[] { "Id", "Players", "PlayersLimit", "Me", });
    internal_static_ecoheroes_JoinRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ecoheroes_JoinRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ecoheroes_JoinRequest_descriptor,
        new java.lang.String[] { "RoomId", });
    internal_static_ecoheroes_RoomsListReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ecoheroes_RoomsListReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ecoheroes_RoomsListReply_descriptor,
        new java.lang.String[] { "Rooms", });
    internal_static_ecoheroes_PlayerInRoomData_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ecoheroes_PlayerInRoomData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ecoheroes_PlayerInRoomData_descriptor,
        new java.lang.String[] { "Number", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
