// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rooms.proto
// Protobuf Java Version: 4.28.3

package com.github.eco_heroes.proto.rooms;

public interface RoomsListReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ecoheroes.RoomsListReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ecoheroes.RoomDataReply rooms = 1;</code>
   */
  java.util.List<com.github.eco_heroes.proto.rooms.RoomDataReply> 
      getRoomsList();
  /**
   * <code>repeated .ecoheroes.RoomDataReply rooms = 1;</code>
   */
  com.github.eco_heroes.proto.rooms.RoomDataReply getRooms(int index);
  /**
   * <code>repeated .ecoheroes.RoomDataReply rooms = 1;</code>
   */
  int getRoomsCount();
  /**
   * <code>repeated .ecoheroes.RoomDataReply rooms = 1;</code>
   */
  java.util.List<? extends com.github.eco_heroes.proto.rooms.RoomDataReplyOrBuilder> 
      getRoomsOrBuilderList();
  /**
   * <code>repeated .ecoheroes.RoomDataReply rooms = 1;</code>
   */
  com.github.eco_heroes.proto.rooms.RoomDataReplyOrBuilder getRoomsOrBuilder(
      int index);
}
