// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: game-events.proto
// Protobuf Java Version: 4.28.3

package com.github.eco_heroes.proto.game_events;

/**
 * Protobuf enum {@code ecoheroes.ContainerType}
 */
public enum ContainerType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>CONTAINER_TYPE_UNKNOWN = 0;</code>
   */
  CONTAINER_TYPE_UNKNOWN(0),
  /**
   * <code>YELLOW = 1;</code>
   */
  YELLOW(1),
  /**
   * <code>GREEN = 2;</code>
   */
  GREEN(2),
  /**
   * <code>BLUE = 3;</code>
   */
  BLUE(3),
  /**
   * <code>DUMP = 4;</code>
   */
  DUMP(4),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      ContainerType.class.getName());
  }
  /**
   * <code>CONTAINER_TYPE_UNKNOWN = 0;</code>
   */
  public static final int CONTAINER_TYPE_UNKNOWN_VALUE = 0;
  /**
   * <code>YELLOW = 1;</code>
   */
  public static final int YELLOW_VALUE = 1;
  /**
   * <code>GREEN = 2;</code>
   */
  public static final int GREEN_VALUE = 2;
  /**
   * <code>BLUE = 3;</code>
   */
  public static final int BLUE_VALUE = 3;
  /**
   * <code>DUMP = 4;</code>
   */
  public static final int DUMP_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ContainerType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ContainerType forNumber(int value) {
    switch (value) {
      case 0: return CONTAINER_TYPE_UNKNOWN;
      case 1: return YELLOW;
      case 2: return GREEN;
      case 3: return BLUE;
      case 4: return DUMP;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ContainerType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ContainerType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ContainerType>() {
          public ContainerType findValueByNumber(int number) {
            return ContainerType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.github.eco_heroes.proto.game_events.GameEventsProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final ContainerType[] VALUES = values();

  public static ContainerType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ContainerType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ecoheroes.ContainerType)
}

