// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: game-events.proto
// Protobuf Java Version: 4.28.2

package com.github.eco_heroes.proto.game_events;

public final class GameEventsProto {
  private GameEventsProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      GameEventsProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ecoheroes_SubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ecoheroes_SubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ecoheroes_ServerEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ecoheroes_ServerEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021game-events.proto\022\tecoheroes\"%\n\023Subscr" +
      "iptionRequest\022\016\n\006roomId\030\001 \001(\t\"\033\n\013ServerE" +
      "vent\022\014\n\004type\030\001 \001(\t2S\n\nGameEvents\022E\n\tsubs" +
      "cribe\022\036.ecoheroes.SubscriptionRequest\032\026." +
      "ecoheroes.ServerEvent0\001BJ\n\'com.github.ec" +
      "o_heroes.proto.game_eventsB\017GameEventsPr" +
      "otoP\001Z\014./gameeventsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ecoheroes_SubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ecoheroes_SubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ecoheroes_SubscriptionRequest_descriptor,
        new java.lang.String[] { "RoomId", });
    internal_static_ecoheroes_ServerEvent_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ecoheroes_ServerEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ecoheroes_ServerEvent_descriptor,
        new java.lang.String[] { "Type", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
