// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: game-events.proto
// Protobuf Java Version: 4.28.3

package com.github.eco_heroes.proto.game_events;

public interface GameEndedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ecoheroes.GameEnded)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 winnerNumber = 1;</code>
   * @return The winnerNumber.
   */
  int getWinnerNumber();
}
