// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: game-events.proto
// Protobuf Java Version: 4.28.3

package com.github.eco_heroes.proto.game_events;

public interface LifeLostOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ecoheroes.LifeLost)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 lives = 1;</code>
   * @return The lives.
   */
  int getLives();

  /**
   * <code>int32 playerNumber = 2;</code>
   * @return The playerNumber.
   */
  int getPlayerNumber();
}
