// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: game-events.proto
// Protobuf Java Version: 4.28.3

package com.github.eco_heroes.proto.game_events;

/**
 * Protobuf type {@code ecoheroes.PlayerRemoved}
 */
public final class PlayerRemoved extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ecoheroes.PlayerRemoved)
    PlayerRemovedOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      PlayerRemoved.class.getName());
  }
  // Use PlayerRemoved.newBuilder() to construct.
  private PlayerRemoved(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PlayerRemoved() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.eco_heroes.proto.game_events.GameEventsProto.internal_static_ecoheroes_PlayerRemoved_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.eco_heroes.proto.game_events.GameEventsProto.internal_static_ecoheroes_PlayerRemoved_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.eco_heroes.proto.game_events.PlayerRemoved.class, com.github.eco_heroes.proto.game_events.PlayerRemoved.Builder.class);
  }

  public static final int PLAYERNUMBER_FIELD_NUMBER = 1;
  private int playerNumber_ = 0;
  /**
   * <code>int32 playerNumber = 1;</code>
   * @return The playerNumber.
   */
  @java.lang.Override
  public int getPlayerNumber() {
    return playerNumber_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (playerNumber_ != 0) {
      output.writeInt32(1, playerNumber_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (playerNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, playerNumber_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.eco_heroes.proto.game_events.PlayerRemoved)) {
      return super.equals(obj);
    }
    com.github.eco_heroes.proto.game_events.PlayerRemoved other = (com.github.eco_heroes.proto.game_events.PlayerRemoved) obj;

    if (getPlayerNumber()
        != other.getPlayerNumber()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PLAYERNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getPlayerNumber();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.eco_heroes.proto.game_events.PlayerRemoved parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.eco_heroes.proto.game_events.PlayerRemoved parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.eco_heroes.proto.game_events.PlayerRemoved parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.eco_heroes.proto.game_events.PlayerRemoved parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.eco_heroes.proto.game_events.PlayerRemoved parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.eco_heroes.proto.game_events.PlayerRemoved parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.eco_heroes.proto.game_events.PlayerRemoved parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.eco_heroes.proto.game_events.PlayerRemoved parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.github.eco_heroes.proto.game_events.PlayerRemoved parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.github.eco_heroes.proto.game_events.PlayerRemoved parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.eco_heroes.proto.game_events.PlayerRemoved parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.eco_heroes.proto.game_events.PlayerRemoved parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.eco_heroes.proto.game_events.PlayerRemoved prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ecoheroes.PlayerRemoved}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ecoheroes.PlayerRemoved)
      com.github.eco_heroes.proto.game_events.PlayerRemovedOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.eco_heroes.proto.game_events.GameEventsProto.internal_static_ecoheroes_PlayerRemoved_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.eco_heroes.proto.game_events.GameEventsProto.internal_static_ecoheroes_PlayerRemoved_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.eco_heroes.proto.game_events.PlayerRemoved.class, com.github.eco_heroes.proto.game_events.PlayerRemoved.Builder.class);
    }

    // Construct using com.github.eco_heroes.proto.game_events.PlayerRemoved.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      playerNumber_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.eco_heroes.proto.game_events.GameEventsProto.internal_static_ecoheroes_PlayerRemoved_descriptor;
    }

    @java.lang.Override
    public com.github.eco_heroes.proto.game_events.PlayerRemoved getDefaultInstanceForType() {
      return com.github.eco_heroes.proto.game_events.PlayerRemoved.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.eco_heroes.proto.game_events.PlayerRemoved build() {
      com.github.eco_heroes.proto.game_events.PlayerRemoved result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.eco_heroes.proto.game_events.PlayerRemoved buildPartial() {
      com.github.eco_heroes.proto.game_events.PlayerRemoved result = new com.github.eco_heroes.proto.game_events.PlayerRemoved(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.github.eco_heroes.proto.game_events.PlayerRemoved result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.playerNumber_ = playerNumber_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.eco_heroes.proto.game_events.PlayerRemoved) {
        return mergeFrom((com.github.eco_heroes.proto.game_events.PlayerRemoved)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.eco_heroes.proto.game_events.PlayerRemoved other) {
      if (other == com.github.eco_heroes.proto.game_events.PlayerRemoved.getDefaultInstance()) return this;
      if (other.getPlayerNumber() != 0) {
        setPlayerNumber(other.getPlayerNumber());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              playerNumber_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int playerNumber_ ;
    /**
     * <code>int32 playerNumber = 1;</code>
     * @return The playerNumber.
     */
    @java.lang.Override
    public int getPlayerNumber() {
      return playerNumber_;
    }
    /**
     * <code>int32 playerNumber = 1;</code>
     * @param value The playerNumber to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerNumber(int value) {

      playerNumber_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 playerNumber = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayerNumber() {
      bitField0_ = (bitField0_ & ~0x00000001);
      playerNumber_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ecoheroes.PlayerRemoved)
  }

  // @@protoc_insertion_point(class_scope:ecoheroes.PlayerRemoved)
  private static final com.github.eco_heroes.proto.game_events.PlayerRemoved DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.eco_heroes.proto.game_events.PlayerRemoved();
  }

  public static com.github.eco_heroes.proto.game_events.PlayerRemoved getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PlayerRemoved>
      PARSER = new com.google.protobuf.AbstractParser<PlayerRemoved>() {
    @java.lang.Override
    public PlayerRemoved parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PlayerRemoved> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PlayerRemoved> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.eco_heroes.proto.game_events.PlayerRemoved getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

