// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: game-events.proto
// Protobuf Java Version: 4.28.3

package com.github.eco_heroes.proto.game_events;

/**
 * Protobuf type {@code ecoheroes.RoomGameDataReply}
 */
public final class RoomGameDataReply extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ecoheroes.RoomGameDataReply)
    RoomGameDataReplyOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      RoomGameDataReply.class.getName());
  }
  // Use RoomGameDataReply.newBuilder() to construct.
  private RoomGameDataReply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RoomGameDataReply() {
    id_ = "";
    players_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.eco_heroes.proto.game_events.GameEventsProto.internal_static_ecoheroes_RoomGameDataReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.eco_heroes.proto.game_events.GameEventsProto.internal_static_ecoheroes_RoomGameDataReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.eco_heroes.proto.game_events.RoomGameDataReply.class, com.github.eco_heroes.proto.game_events.RoomGameDataReply.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLAYERS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.github.eco_heroes.proto.game_events.PlayerInRoomGameData> players_;
  /**
   * <code>repeated .ecoheroes.PlayerInRoomGameData players = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.github.eco_heroes.proto.game_events.PlayerInRoomGameData> getPlayersList() {
    return players_;
  }
  /**
   * <code>repeated .ecoheroes.PlayerInRoomGameData players = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.github.eco_heroes.proto.game_events.PlayerInRoomGameDataOrBuilder> 
      getPlayersOrBuilderList() {
    return players_;
  }
  /**
   * <code>repeated .ecoheroes.PlayerInRoomGameData players = 2;</code>
   */
  @java.lang.Override
  public int getPlayersCount() {
    return players_.size();
  }
  /**
   * <code>repeated .ecoheroes.PlayerInRoomGameData players = 2;</code>
   */
  @java.lang.Override
  public com.github.eco_heroes.proto.game_events.PlayerInRoomGameData getPlayers(int index) {
    return players_.get(index);
  }
  /**
   * <code>repeated .ecoheroes.PlayerInRoomGameData players = 2;</code>
   */
  @java.lang.Override
  public com.github.eco_heroes.proto.game_events.PlayerInRoomGameDataOrBuilder getPlayersOrBuilder(
      int index) {
    return players_.get(index);
  }

  public static final int PLAYERSLIMIT_FIELD_NUMBER = 3;
  private int playersLimit_ = 0;
  /**
   * <code>int32 playersLimit = 3;</code>
   * @return The playersLimit.
   */
  @java.lang.Override
  public int getPlayersLimit() {
    return playersLimit_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
    }
    for (int i = 0; i < players_.size(); i++) {
      output.writeMessage(2, players_.get(i));
    }
    if (playersLimit_ != 0) {
      output.writeInt32(3, playersLimit_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
    }
    for (int i = 0; i < players_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, players_.get(i));
    }
    if (playersLimit_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, playersLimit_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.eco_heroes.proto.game_events.RoomGameDataReply)) {
      return super.equals(obj);
    }
    com.github.eco_heroes.proto.game_events.RoomGameDataReply other = (com.github.eco_heroes.proto.game_events.RoomGameDataReply) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getPlayersList()
        .equals(other.getPlayersList())) return false;
    if (getPlayersLimit()
        != other.getPlayersLimit()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (getPlayersCount() > 0) {
      hash = (37 * hash) + PLAYERS_FIELD_NUMBER;
      hash = (53 * hash) + getPlayersList().hashCode();
    }
    hash = (37 * hash) + PLAYERSLIMIT_FIELD_NUMBER;
    hash = (53 * hash) + getPlayersLimit();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.eco_heroes.proto.game_events.RoomGameDataReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.eco_heroes.proto.game_events.RoomGameDataReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.eco_heroes.proto.game_events.RoomGameDataReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.eco_heroes.proto.game_events.RoomGameDataReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.eco_heroes.proto.game_events.RoomGameDataReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.eco_heroes.proto.game_events.RoomGameDataReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.eco_heroes.proto.game_events.RoomGameDataReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.eco_heroes.proto.game_events.RoomGameDataReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.github.eco_heroes.proto.game_events.RoomGameDataReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.github.eco_heroes.proto.game_events.RoomGameDataReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.eco_heroes.proto.game_events.RoomGameDataReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.eco_heroes.proto.game_events.RoomGameDataReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.eco_heroes.proto.game_events.RoomGameDataReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ecoheroes.RoomGameDataReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ecoheroes.RoomGameDataReply)
      com.github.eco_heroes.proto.game_events.RoomGameDataReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.eco_heroes.proto.game_events.GameEventsProto.internal_static_ecoheroes_RoomGameDataReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.eco_heroes.proto.game_events.GameEventsProto.internal_static_ecoheroes_RoomGameDataReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.eco_heroes.proto.game_events.RoomGameDataReply.class, com.github.eco_heroes.proto.game_events.RoomGameDataReply.Builder.class);
    }

    // Construct using com.github.eco_heroes.proto.game_events.RoomGameDataReply.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      if (playersBuilder_ == null) {
        players_ = java.util.Collections.emptyList();
      } else {
        players_ = null;
        playersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      playersLimit_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.eco_heroes.proto.game_events.GameEventsProto.internal_static_ecoheroes_RoomGameDataReply_descriptor;
    }

    @java.lang.Override
    public com.github.eco_heroes.proto.game_events.RoomGameDataReply getDefaultInstanceForType() {
      return com.github.eco_heroes.proto.game_events.RoomGameDataReply.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.eco_heroes.proto.game_events.RoomGameDataReply build() {
      com.github.eco_heroes.proto.game_events.RoomGameDataReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.eco_heroes.proto.game_events.RoomGameDataReply buildPartial() {
      com.github.eco_heroes.proto.game_events.RoomGameDataReply result = new com.github.eco_heroes.proto.game_events.RoomGameDataReply(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.github.eco_heroes.proto.game_events.RoomGameDataReply result) {
      if (playersBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          players_ = java.util.Collections.unmodifiableList(players_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.players_ = players_;
      } else {
        result.players_ = playersBuilder_.build();
      }
    }

    private void buildPartial0(com.github.eco_heroes.proto.game_events.RoomGameDataReply result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.playersLimit_ = playersLimit_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.eco_heroes.proto.game_events.RoomGameDataReply) {
        return mergeFrom((com.github.eco_heroes.proto.game_events.RoomGameDataReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.eco_heroes.proto.game_events.RoomGameDataReply other) {
      if (other == com.github.eco_heroes.proto.game_events.RoomGameDataReply.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (playersBuilder_ == null) {
        if (!other.players_.isEmpty()) {
          if (players_.isEmpty()) {
            players_ = other.players_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePlayersIsMutable();
            players_.addAll(other.players_);
          }
          onChanged();
        }
      } else {
        if (!other.players_.isEmpty()) {
          if (playersBuilder_.isEmpty()) {
            playersBuilder_.dispose();
            playersBuilder_ = null;
            players_ = other.players_;
            bitField0_ = (bitField0_ & ~0x00000002);
            playersBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getPlayersFieldBuilder() : null;
          } else {
            playersBuilder_.addAllMessages(other.players_);
          }
        }
      }
      if (other.getPlayersLimit() != 0) {
        setPlayersLimit(other.getPlayersLimit());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.github.eco_heroes.proto.game_events.PlayerInRoomGameData m =
                  input.readMessage(
                      com.github.eco_heroes.proto.game_events.PlayerInRoomGameData.parser(),
                      extensionRegistry);
              if (playersBuilder_ == null) {
                ensurePlayersIsMutable();
                players_.add(m);
              } else {
                playersBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 24: {
              playersLimit_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<com.github.eco_heroes.proto.game_events.PlayerInRoomGameData> players_ =
      java.util.Collections.emptyList();
    private void ensurePlayersIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        players_ = new java.util.ArrayList<com.github.eco_heroes.proto.game_events.PlayerInRoomGameData>(players_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.github.eco_heroes.proto.game_events.PlayerInRoomGameData, com.github.eco_heroes.proto.game_events.PlayerInRoomGameData.Builder, com.github.eco_heroes.proto.game_events.PlayerInRoomGameDataOrBuilder> playersBuilder_;

    /**
     * <code>repeated .ecoheroes.PlayerInRoomGameData players = 2;</code>
     */
    public java.util.List<com.github.eco_heroes.proto.game_events.PlayerInRoomGameData> getPlayersList() {
      if (playersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(players_);
      } else {
        return playersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ecoheroes.PlayerInRoomGameData players = 2;</code>
     */
    public int getPlayersCount() {
      if (playersBuilder_ == null) {
        return players_.size();
      } else {
        return playersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ecoheroes.PlayerInRoomGameData players = 2;</code>
     */
    public com.github.eco_heroes.proto.game_events.PlayerInRoomGameData getPlayers(int index) {
      if (playersBuilder_ == null) {
        return players_.get(index);
      } else {
        return playersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ecoheroes.PlayerInRoomGameData players = 2;</code>
     */
    public Builder setPlayers(
        int index, com.github.eco_heroes.proto.game_events.PlayerInRoomGameData value) {
      if (playersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayersIsMutable();
        players_.set(index, value);
        onChanged();
      } else {
        playersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ecoheroes.PlayerInRoomGameData players = 2;</code>
     */
    public Builder setPlayers(
        int index, com.github.eco_heroes.proto.game_events.PlayerInRoomGameData.Builder builderForValue) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.set(index, builderForValue.build());
        onChanged();
      } else {
        playersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ecoheroes.PlayerInRoomGameData players = 2;</code>
     */
    public Builder addPlayers(com.github.eco_heroes.proto.game_events.PlayerInRoomGameData value) {
      if (playersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayersIsMutable();
        players_.add(value);
        onChanged();
      } else {
        playersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ecoheroes.PlayerInRoomGameData players = 2;</code>
     */
    public Builder addPlayers(
        int index, com.github.eco_heroes.proto.game_events.PlayerInRoomGameData value) {
      if (playersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayersIsMutable();
        players_.add(index, value);
        onChanged();
      } else {
        playersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ecoheroes.PlayerInRoomGameData players = 2;</code>
     */
    public Builder addPlayers(
        com.github.eco_heroes.proto.game_events.PlayerInRoomGameData.Builder builderForValue) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.add(builderForValue.build());
        onChanged();
      } else {
        playersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ecoheroes.PlayerInRoomGameData players = 2;</code>
     */
    public Builder addPlayers(
        int index, com.github.eco_heroes.proto.game_events.PlayerInRoomGameData.Builder builderForValue) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.add(index, builderForValue.build());
        onChanged();
      } else {
        playersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ecoheroes.PlayerInRoomGameData players = 2;</code>
     */
    public Builder addAllPlayers(
        java.lang.Iterable<? extends com.github.eco_heroes.proto.game_events.PlayerInRoomGameData> values) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, players_);
        onChanged();
      } else {
        playersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ecoheroes.PlayerInRoomGameData players = 2;</code>
     */
    public Builder clearPlayers() {
      if (playersBuilder_ == null) {
        players_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        playersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ecoheroes.PlayerInRoomGameData players = 2;</code>
     */
    public Builder removePlayers(int index) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.remove(index);
        onChanged();
      } else {
        playersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ecoheroes.PlayerInRoomGameData players = 2;</code>
     */
    public com.github.eco_heroes.proto.game_events.PlayerInRoomGameData.Builder getPlayersBuilder(
        int index) {
      return getPlayersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ecoheroes.PlayerInRoomGameData players = 2;</code>
     */
    public com.github.eco_heroes.proto.game_events.PlayerInRoomGameDataOrBuilder getPlayersOrBuilder(
        int index) {
      if (playersBuilder_ == null) {
        return players_.get(index);  } else {
        return playersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ecoheroes.PlayerInRoomGameData players = 2;</code>
     */
    public java.util.List<? extends com.github.eco_heroes.proto.game_events.PlayerInRoomGameDataOrBuilder> 
         getPlayersOrBuilderList() {
      if (playersBuilder_ != null) {
        return playersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(players_);
      }
    }
    /**
     * <code>repeated .ecoheroes.PlayerInRoomGameData players = 2;</code>
     */
    public com.github.eco_heroes.proto.game_events.PlayerInRoomGameData.Builder addPlayersBuilder() {
      return getPlayersFieldBuilder().addBuilder(
          com.github.eco_heroes.proto.game_events.PlayerInRoomGameData.getDefaultInstance());
    }
    /**
     * <code>repeated .ecoheroes.PlayerInRoomGameData players = 2;</code>
     */
    public com.github.eco_heroes.proto.game_events.PlayerInRoomGameData.Builder addPlayersBuilder(
        int index) {
      return getPlayersFieldBuilder().addBuilder(
          index, com.github.eco_heroes.proto.game_events.PlayerInRoomGameData.getDefaultInstance());
    }
    /**
     * <code>repeated .ecoheroes.PlayerInRoomGameData players = 2;</code>
     */
    public java.util.List<com.github.eco_heroes.proto.game_events.PlayerInRoomGameData.Builder> 
         getPlayersBuilderList() {
      return getPlayersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.github.eco_heroes.proto.game_events.PlayerInRoomGameData, com.github.eco_heroes.proto.game_events.PlayerInRoomGameData.Builder, com.github.eco_heroes.proto.game_events.PlayerInRoomGameDataOrBuilder> 
        getPlayersFieldBuilder() {
      if (playersBuilder_ == null) {
        playersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.github.eco_heroes.proto.game_events.PlayerInRoomGameData, com.github.eco_heroes.proto.game_events.PlayerInRoomGameData.Builder, com.github.eco_heroes.proto.game_events.PlayerInRoomGameDataOrBuilder>(
                players_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        players_ = null;
      }
      return playersBuilder_;
    }

    private int playersLimit_ ;
    /**
     * <code>int32 playersLimit = 3;</code>
     * @return The playersLimit.
     */
    @java.lang.Override
    public int getPlayersLimit() {
      return playersLimit_;
    }
    /**
     * <code>int32 playersLimit = 3;</code>
     * @param value The playersLimit to set.
     * @return This builder for chaining.
     */
    public Builder setPlayersLimit(int value) {

      playersLimit_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 playersLimit = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayersLimit() {
      bitField0_ = (bitField0_ & ~0x00000004);
      playersLimit_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ecoheroes.RoomGameDataReply)
  }

  // @@protoc_insertion_point(class_scope:ecoheroes.RoomGameDataReply)
  private static final com.github.eco_heroes.proto.game_events.RoomGameDataReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.eco_heroes.proto.game_events.RoomGameDataReply();
  }

  public static com.github.eco_heroes.proto.game_events.RoomGameDataReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RoomGameDataReply>
      PARSER = new com.google.protobuf.AbstractParser<RoomGameDataReply>() {
    @java.lang.Override
    public RoomGameDataReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RoomGameDataReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RoomGameDataReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.eco_heroes.proto.game_events.RoomGameDataReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

