// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: game-events.proto
// Protobuf Java Version: 4.28.2

package com.github.eco_heroes.proto.game_events;

public interface ServerEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ecoheroes.ServerEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * TODO: Make this an enum.
   * </pre>
   *
   * <code>string type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <pre>
   * TODO: Make this an enum.
   * </pre>
   *
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
