// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: game-events.proto
// Protobuf Java Version: 4.28.3

package com.github.eco_heroes.proto.game_events;

/**
 * Protobuf type {@code ecoheroes.ServerEvent}
 */
public final class ServerEvent extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ecoheroes.ServerEvent)
    ServerEventOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      ServerEvent.class.getName());
  }
  // Use ServerEvent.newBuilder() to construct.
  private ServerEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ServerEvent() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.eco_heroes.proto.game_events.GameEventsProto.internal_static_ecoheroes_ServerEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.eco_heroes.proto.game_events.GameEventsProto.internal_static_ecoheroes_ServerEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.eco_heroes.proto.game_events.ServerEvent.class, com.github.eco_heroes.proto.game_events.ServerEvent.Builder.class);
  }

  private int eventCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object event_;
  public enum EventCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    UNSPECIFIEDEVT(1),
    PLAYERADDEDEVT(2),
    PLAYERREMOVEDEVT(3),
    GAMESTARTEDEVT(4),
    WASTEGENERATEDEVT(5),
    LIFELOSTEVT(6),
    SPEEDINCREASEDEVT(7),
    GAMEENDEDEVT(8),
    EVENT_NOT_SET(0);
    private final int value;
    private EventCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EventCase valueOf(int value) {
      return forNumber(value);
    }

    public static EventCase forNumber(int value) {
      switch (value) {
        case 1: return UNSPECIFIEDEVT;
        case 2: return PLAYERADDEDEVT;
        case 3: return PLAYERREMOVEDEVT;
        case 4: return GAMESTARTEDEVT;
        case 5: return WASTEGENERATEDEVT;
        case 6: return LIFELOSTEVT;
        case 7: return SPEEDINCREASEDEVT;
        case 8: return GAMEENDEDEVT;
        case 0: return EVENT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public EventCase
  getEventCase() {
    return EventCase.forNumber(
        eventCase_);
  }

  public static final int UNSPECIFIEDEVT_FIELD_NUMBER = 1;
  /**
   * <code>.ecoheroes.Unspecified unspecifiedEvt = 1;</code>
   * @return Whether the unspecifiedEvt field is set.
   */
  @java.lang.Override
  public boolean hasUnspecifiedEvt() {
    return eventCase_ == 1;
  }
  /**
   * <code>.ecoheroes.Unspecified unspecifiedEvt = 1;</code>
   * @return The unspecifiedEvt.
   */
  @java.lang.Override
  public com.github.eco_heroes.proto.game_events.Unspecified getUnspecifiedEvt() {
    if (eventCase_ == 1) {
       return (com.github.eco_heroes.proto.game_events.Unspecified) event_;
    }
    return com.github.eco_heroes.proto.game_events.Unspecified.getDefaultInstance();
  }
  /**
   * <code>.ecoheroes.Unspecified unspecifiedEvt = 1;</code>
   */
  @java.lang.Override
  public com.github.eco_heroes.proto.game_events.UnspecifiedOrBuilder getUnspecifiedEvtOrBuilder() {
    if (eventCase_ == 1) {
       return (com.github.eco_heroes.proto.game_events.Unspecified) event_;
    }
    return com.github.eco_heroes.proto.game_events.Unspecified.getDefaultInstance();
  }

  public static final int PLAYERADDEDEVT_FIELD_NUMBER = 2;
  /**
   * <code>.ecoheroes.PlayerAdded playerAddedEvt = 2;</code>
   * @return Whether the playerAddedEvt field is set.
   */
  @java.lang.Override
  public boolean hasPlayerAddedEvt() {
    return eventCase_ == 2;
  }
  /**
   * <code>.ecoheroes.PlayerAdded playerAddedEvt = 2;</code>
   * @return The playerAddedEvt.
   */
  @java.lang.Override
  public com.github.eco_heroes.proto.game_events.PlayerAdded getPlayerAddedEvt() {
    if (eventCase_ == 2) {
       return (com.github.eco_heroes.proto.game_events.PlayerAdded) event_;
    }
    return com.github.eco_heroes.proto.game_events.PlayerAdded.getDefaultInstance();
  }
  /**
   * <code>.ecoheroes.PlayerAdded playerAddedEvt = 2;</code>
   */
  @java.lang.Override
  public com.github.eco_heroes.proto.game_events.PlayerAddedOrBuilder getPlayerAddedEvtOrBuilder() {
    if (eventCase_ == 2) {
       return (com.github.eco_heroes.proto.game_events.PlayerAdded) event_;
    }
    return com.github.eco_heroes.proto.game_events.PlayerAdded.getDefaultInstance();
  }

  public static final int PLAYERREMOVEDEVT_FIELD_NUMBER = 3;
  /**
   * <code>.ecoheroes.PlayerRemoved playerRemovedEvt = 3;</code>
   * @return Whether the playerRemovedEvt field is set.
   */
  @java.lang.Override
  public boolean hasPlayerRemovedEvt() {
    return eventCase_ == 3;
  }
  /**
   * <code>.ecoheroes.PlayerRemoved playerRemovedEvt = 3;</code>
   * @return The playerRemovedEvt.
   */
  @java.lang.Override
  public com.github.eco_heroes.proto.game_events.PlayerRemoved getPlayerRemovedEvt() {
    if (eventCase_ == 3) {
       return (com.github.eco_heroes.proto.game_events.PlayerRemoved) event_;
    }
    return com.github.eco_heroes.proto.game_events.PlayerRemoved.getDefaultInstance();
  }
  /**
   * <code>.ecoheroes.PlayerRemoved playerRemovedEvt = 3;</code>
   */
  @java.lang.Override
  public com.github.eco_heroes.proto.game_events.PlayerRemovedOrBuilder getPlayerRemovedEvtOrBuilder() {
    if (eventCase_ == 3) {
       return (com.github.eco_heroes.proto.game_events.PlayerRemoved) event_;
    }
    return com.github.eco_heroes.proto.game_events.PlayerRemoved.getDefaultInstance();
  }

  public static final int GAMESTARTEDEVT_FIELD_NUMBER = 4;
  /**
   * <code>.ecoheroes.GameStarted gameStartedEvt = 4;</code>
   * @return Whether the gameStartedEvt field is set.
   */
  @java.lang.Override
  public boolean hasGameStartedEvt() {
    return eventCase_ == 4;
  }
  /**
   * <code>.ecoheroes.GameStarted gameStartedEvt = 4;</code>
   * @return The gameStartedEvt.
   */
  @java.lang.Override
  public com.github.eco_heroes.proto.game_events.GameStarted getGameStartedEvt() {
    if (eventCase_ == 4) {
       return (com.github.eco_heroes.proto.game_events.GameStarted) event_;
    }
    return com.github.eco_heroes.proto.game_events.GameStarted.getDefaultInstance();
  }
  /**
   * <code>.ecoheroes.GameStarted gameStartedEvt = 4;</code>
   */
  @java.lang.Override
  public com.github.eco_heroes.proto.game_events.GameStartedOrBuilder getGameStartedEvtOrBuilder() {
    if (eventCase_ == 4) {
       return (com.github.eco_heroes.proto.game_events.GameStarted) event_;
    }
    return com.github.eco_heroes.proto.game_events.GameStarted.getDefaultInstance();
  }

  public static final int WASTEGENERATEDEVT_FIELD_NUMBER = 5;
  /**
   * <code>.ecoheroes.WasteGenerated wasteGeneratedEvt = 5;</code>
   * @return Whether the wasteGeneratedEvt field is set.
   */
  @java.lang.Override
  public boolean hasWasteGeneratedEvt() {
    return eventCase_ == 5;
  }
  /**
   * <code>.ecoheroes.WasteGenerated wasteGeneratedEvt = 5;</code>
   * @return The wasteGeneratedEvt.
   */
  @java.lang.Override
  public com.github.eco_heroes.proto.game_events.WasteGenerated getWasteGeneratedEvt() {
    if (eventCase_ == 5) {
       return (com.github.eco_heroes.proto.game_events.WasteGenerated) event_;
    }
    return com.github.eco_heroes.proto.game_events.WasteGenerated.getDefaultInstance();
  }
  /**
   * <code>.ecoheroes.WasteGenerated wasteGeneratedEvt = 5;</code>
   */
  @java.lang.Override
  public com.github.eco_heroes.proto.game_events.WasteGeneratedOrBuilder getWasteGeneratedEvtOrBuilder() {
    if (eventCase_ == 5) {
       return (com.github.eco_heroes.proto.game_events.WasteGenerated) event_;
    }
    return com.github.eco_heroes.proto.game_events.WasteGenerated.getDefaultInstance();
  }

  public static final int LIFELOSTEVT_FIELD_NUMBER = 6;
  /**
   * <code>.ecoheroes.LifeLost lifeLostEvt = 6;</code>
   * @return Whether the lifeLostEvt field is set.
   */
  @java.lang.Override
  public boolean hasLifeLostEvt() {
    return eventCase_ == 6;
  }
  /**
   * <code>.ecoheroes.LifeLost lifeLostEvt = 6;</code>
   * @return The lifeLostEvt.
   */
  @java.lang.Override
  public com.github.eco_heroes.proto.game_events.LifeLost getLifeLostEvt() {
    if (eventCase_ == 6) {
       return (com.github.eco_heroes.proto.game_events.LifeLost) event_;
    }
    return com.github.eco_heroes.proto.game_events.LifeLost.getDefaultInstance();
  }
  /**
   * <code>.ecoheroes.LifeLost lifeLostEvt = 6;</code>
   */
  @java.lang.Override
  public com.github.eco_heroes.proto.game_events.LifeLostOrBuilder getLifeLostEvtOrBuilder() {
    if (eventCase_ == 6) {
       return (com.github.eco_heroes.proto.game_events.LifeLost) event_;
    }
    return com.github.eco_heroes.proto.game_events.LifeLost.getDefaultInstance();
  }

  public static final int SPEEDINCREASEDEVT_FIELD_NUMBER = 7;
  /**
   * <code>.ecoheroes.SpeedIncreased speedIncreasedEvt = 7;</code>
   * @return Whether the speedIncreasedEvt field is set.
   */
  @java.lang.Override
  public boolean hasSpeedIncreasedEvt() {
    return eventCase_ == 7;
  }
  /**
   * <code>.ecoheroes.SpeedIncreased speedIncreasedEvt = 7;</code>
   * @return The speedIncreasedEvt.
   */
  @java.lang.Override
  public com.github.eco_heroes.proto.game_events.SpeedIncreased getSpeedIncreasedEvt() {
    if (eventCase_ == 7) {
       return (com.github.eco_heroes.proto.game_events.SpeedIncreased) event_;
    }
    return com.github.eco_heroes.proto.game_events.SpeedIncreased.getDefaultInstance();
  }
  /**
   * <code>.ecoheroes.SpeedIncreased speedIncreasedEvt = 7;</code>
   */
  @java.lang.Override
  public com.github.eco_heroes.proto.game_events.SpeedIncreasedOrBuilder getSpeedIncreasedEvtOrBuilder() {
    if (eventCase_ == 7) {
       return (com.github.eco_heroes.proto.game_events.SpeedIncreased) event_;
    }
    return com.github.eco_heroes.proto.game_events.SpeedIncreased.getDefaultInstance();
  }

  public static final int GAMEENDEDEVT_FIELD_NUMBER = 8;
  /**
   * <code>.ecoheroes.GameEnded gameEndedEvt = 8;</code>
   * @return Whether the gameEndedEvt field is set.
   */
  @java.lang.Override
  public boolean hasGameEndedEvt() {
    return eventCase_ == 8;
  }
  /**
   * <code>.ecoheroes.GameEnded gameEndedEvt = 8;</code>
   * @return The gameEndedEvt.
   */
  @java.lang.Override
  public com.github.eco_heroes.proto.game_events.GameEnded getGameEndedEvt() {
    if (eventCase_ == 8) {
       return (com.github.eco_heroes.proto.game_events.GameEnded) event_;
    }
    return com.github.eco_heroes.proto.game_events.GameEnded.getDefaultInstance();
  }
  /**
   * <code>.ecoheroes.GameEnded gameEndedEvt = 8;</code>
   */
  @java.lang.Override
  public com.github.eco_heroes.proto.game_events.GameEndedOrBuilder getGameEndedEvtOrBuilder() {
    if (eventCase_ == 8) {
       return (com.github.eco_heroes.proto.game_events.GameEnded) event_;
    }
    return com.github.eco_heroes.proto.game_events.GameEnded.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (eventCase_ == 1) {
      output.writeMessage(1, (com.github.eco_heroes.proto.game_events.Unspecified) event_);
    }
    if (eventCase_ == 2) {
      output.writeMessage(2, (com.github.eco_heroes.proto.game_events.PlayerAdded) event_);
    }
    if (eventCase_ == 3) {
      output.writeMessage(3, (com.github.eco_heroes.proto.game_events.PlayerRemoved) event_);
    }
    if (eventCase_ == 4) {
      output.writeMessage(4, (com.github.eco_heroes.proto.game_events.GameStarted) event_);
    }
    if (eventCase_ == 5) {
      output.writeMessage(5, (com.github.eco_heroes.proto.game_events.WasteGenerated) event_);
    }
    if (eventCase_ == 6) {
      output.writeMessage(6, (com.github.eco_heroes.proto.game_events.LifeLost) event_);
    }
    if (eventCase_ == 7) {
      output.writeMessage(7, (com.github.eco_heroes.proto.game_events.SpeedIncreased) event_);
    }
    if (eventCase_ == 8) {
      output.writeMessage(8, (com.github.eco_heroes.proto.game_events.GameEnded) event_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (eventCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.github.eco_heroes.proto.game_events.Unspecified) event_);
    }
    if (eventCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.github.eco_heroes.proto.game_events.PlayerAdded) event_);
    }
    if (eventCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.github.eco_heroes.proto.game_events.PlayerRemoved) event_);
    }
    if (eventCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.github.eco_heroes.proto.game_events.GameStarted) event_);
    }
    if (eventCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (com.github.eco_heroes.proto.game_events.WasteGenerated) event_);
    }
    if (eventCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (com.github.eco_heroes.proto.game_events.LifeLost) event_);
    }
    if (eventCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (com.github.eco_heroes.proto.game_events.SpeedIncreased) event_);
    }
    if (eventCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, (com.github.eco_heroes.proto.game_events.GameEnded) event_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.eco_heroes.proto.game_events.ServerEvent)) {
      return super.equals(obj);
    }
    com.github.eco_heroes.proto.game_events.ServerEvent other = (com.github.eco_heroes.proto.game_events.ServerEvent) obj;

    if (!getEventCase().equals(other.getEventCase())) return false;
    switch (eventCase_) {
      case 1:
        if (!getUnspecifiedEvt()
            .equals(other.getUnspecifiedEvt())) return false;
        break;
      case 2:
        if (!getPlayerAddedEvt()
            .equals(other.getPlayerAddedEvt())) return false;
        break;
      case 3:
        if (!getPlayerRemovedEvt()
            .equals(other.getPlayerRemovedEvt())) return false;
        break;
      case 4:
        if (!getGameStartedEvt()
            .equals(other.getGameStartedEvt())) return false;
        break;
      case 5:
        if (!getWasteGeneratedEvt()
            .equals(other.getWasteGeneratedEvt())) return false;
        break;
      case 6:
        if (!getLifeLostEvt()
            .equals(other.getLifeLostEvt())) return false;
        break;
      case 7:
        if (!getSpeedIncreasedEvt()
            .equals(other.getSpeedIncreasedEvt())) return false;
        break;
      case 8:
        if (!getGameEndedEvt()
            .equals(other.getGameEndedEvt())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (eventCase_) {
      case 1:
        hash = (37 * hash) + UNSPECIFIEDEVT_FIELD_NUMBER;
        hash = (53 * hash) + getUnspecifiedEvt().hashCode();
        break;
      case 2:
        hash = (37 * hash) + PLAYERADDEDEVT_FIELD_NUMBER;
        hash = (53 * hash) + getPlayerAddedEvt().hashCode();
        break;
      case 3:
        hash = (37 * hash) + PLAYERREMOVEDEVT_FIELD_NUMBER;
        hash = (53 * hash) + getPlayerRemovedEvt().hashCode();
        break;
      case 4:
        hash = (37 * hash) + GAMESTARTEDEVT_FIELD_NUMBER;
        hash = (53 * hash) + getGameStartedEvt().hashCode();
        break;
      case 5:
        hash = (37 * hash) + WASTEGENERATEDEVT_FIELD_NUMBER;
        hash = (53 * hash) + getWasteGeneratedEvt().hashCode();
        break;
      case 6:
        hash = (37 * hash) + LIFELOSTEVT_FIELD_NUMBER;
        hash = (53 * hash) + getLifeLostEvt().hashCode();
        break;
      case 7:
        hash = (37 * hash) + SPEEDINCREASEDEVT_FIELD_NUMBER;
        hash = (53 * hash) + getSpeedIncreasedEvt().hashCode();
        break;
      case 8:
        hash = (37 * hash) + GAMEENDEDEVT_FIELD_NUMBER;
        hash = (53 * hash) + getGameEndedEvt().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.eco_heroes.proto.game_events.ServerEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.eco_heroes.proto.game_events.ServerEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.eco_heroes.proto.game_events.ServerEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.eco_heroes.proto.game_events.ServerEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.eco_heroes.proto.game_events.ServerEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.eco_heroes.proto.game_events.ServerEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.eco_heroes.proto.game_events.ServerEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.eco_heroes.proto.game_events.ServerEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.github.eco_heroes.proto.game_events.ServerEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.github.eco_heroes.proto.game_events.ServerEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.eco_heroes.proto.game_events.ServerEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.eco_heroes.proto.game_events.ServerEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.eco_heroes.proto.game_events.ServerEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ecoheroes.ServerEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ecoheroes.ServerEvent)
      com.github.eco_heroes.proto.game_events.ServerEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.eco_heroes.proto.game_events.GameEventsProto.internal_static_ecoheroes_ServerEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.eco_heroes.proto.game_events.GameEventsProto.internal_static_ecoheroes_ServerEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.eco_heroes.proto.game_events.ServerEvent.class, com.github.eco_heroes.proto.game_events.ServerEvent.Builder.class);
    }

    // Construct using com.github.eco_heroes.proto.game_events.ServerEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (unspecifiedEvtBuilder_ != null) {
        unspecifiedEvtBuilder_.clear();
      }
      if (playerAddedEvtBuilder_ != null) {
        playerAddedEvtBuilder_.clear();
      }
      if (playerRemovedEvtBuilder_ != null) {
        playerRemovedEvtBuilder_.clear();
      }
      if (gameStartedEvtBuilder_ != null) {
        gameStartedEvtBuilder_.clear();
      }
      if (wasteGeneratedEvtBuilder_ != null) {
        wasteGeneratedEvtBuilder_.clear();
      }
      if (lifeLostEvtBuilder_ != null) {
        lifeLostEvtBuilder_.clear();
      }
      if (speedIncreasedEvtBuilder_ != null) {
        speedIncreasedEvtBuilder_.clear();
      }
      if (gameEndedEvtBuilder_ != null) {
        gameEndedEvtBuilder_.clear();
      }
      eventCase_ = 0;
      event_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.eco_heroes.proto.game_events.GameEventsProto.internal_static_ecoheroes_ServerEvent_descriptor;
    }

    @java.lang.Override
    public com.github.eco_heroes.proto.game_events.ServerEvent getDefaultInstanceForType() {
      return com.github.eco_heroes.proto.game_events.ServerEvent.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.eco_heroes.proto.game_events.ServerEvent build() {
      com.github.eco_heroes.proto.game_events.ServerEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.eco_heroes.proto.game_events.ServerEvent buildPartial() {
      com.github.eco_heroes.proto.game_events.ServerEvent result = new com.github.eco_heroes.proto.game_events.ServerEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.github.eco_heroes.proto.game_events.ServerEvent result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.github.eco_heroes.proto.game_events.ServerEvent result) {
      result.eventCase_ = eventCase_;
      result.event_ = this.event_;
      if (eventCase_ == 1 &&
          unspecifiedEvtBuilder_ != null) {
        result.event_ = unspecifiedEvtBuilder_.build();
      }
      if (eventCase_ == 2 &&
          playerAddedEvtBuilder_ != null) {
        result.event_ = playerAddedEvtBuilder_.build();
      }
      if (eventCase_ == 3 &&
          playerRemovedEvtBuilder_ != null) {
        result.event_ = playerRemovedEvtBuilder_.build();
      }
      if (eventCase_ == 4 &&
          gameStartedEvtBuilder_ != null) {
        result.event_ = gameStartedEvtBuilder_.build();
      }
      if (eventCase_ == 5 &&
          wasteGeneratedEvtBuilder_ != null) {
        result.event_ = wasteGeneratedEvtBuilder_.build();
      }
      if (eventCase_ == 6 &&
          lifeLostEvtBuilder_ != null) {
        result.event_ = lifeLostEvtBuilder_.build();
      }
      if (eventCase_ == 7 &&
          speedIncreasedEvtBuilder_ != null) {
        result.event_ = speedIncreasedEvtBuilder_.build();
      }
      if (eventCase_ == 8 &&
          gameEndedEvtBuilder_ != null) {
        result.event_ = gameEndedEvtBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.eco_heroes.proto.game_events.ServerEvent) {
        return mergeFrom((com.github.eco_heroes.proto.game_events.ServerEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.eco_heroes.proto.game_events.ServerEvent other) {
      if (other == com.github.eco_heroes.proto.game_events.ServerEvent.getDefaultInstance()) return this;
      switch (other.getEventCase()) {
        case UNSPECIFIEDEVT: {
          mergeUnspecifiedEvt(other.getUnspecifiedEvt());
          break;
        }
        case PLAYERADDEDEVT: {
          mergePlayerAddedEvt(other.getPlayerAddedEvt());
          break;
        }
        case PLAYERREMOVEDEVT: {
          mergePlayerRemovedEvt(other.getPlayerRemovedEvt());
          break;
        }
        case GAMESTARTEDEVT: {
          mergeGameStartedEvt(other.getGameStartedEvt());
          break;
        }
        case WASTEGENERATEDEVT: {
          mergeWasteGeneratedEvt(other.getWasteGeneratedEvt());
          break;
        }
        case LIFELOSTEVT: {
          mergeLifeLostEvt(other.getLifeLostEvt());
          break;
        }
        case SPEEDINCREASEDEVT: {
          mergeSpeedIncreasedEvt(other.getSpeedIncreasedEvt());
          break;
        }
        case GAMEENDEDEVT: {
          mergeGameEndedEvt(other.getGameEndedEvt());
          break;
        }
        case EVENT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getUnspecifiedEvtFieldBuilder().getBuilder(),
                  extensionRegistry);
              eventCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getPlayerAddedEvtFieldBuilder().getBuilder(),
                  extensionRegistry);
              eventCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getPlayerRemovedEvtFieldBuilder().getBuilder(),
                  extensionRegistry);
              eventCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getGameStartedEvtFieldBuilder().getBuilder(),
                  extensionRegistry);
              eventCase_ = 4;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getWasteGeneratedEvtFieldBuilder().getBuilder(),
                  extensionRegistry);
              eventCase_ = 5;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getLifeLostEvtFieldBuilder().getBuilder(),
                  extensionRegistry);
              eventCase_ = 6;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getSpeedIncreasedEvtFieldBuilder().getBuilder(),
                  extensionRegistry);
              eventCase_ = 7;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  getGameEndedEvtFieldBuilder().getBuilder(),
                  extensionRegistry);
              eventCase_ = 8;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int eventCase_ = 0;
    private java.lang.Object event_;
    public EventCase
        getEventCase() {
      return EventCase.forNumber(
          eventCase_);
    }

    public Builder clearEvent() {
      eventCase_ = 0;
      event_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilder<
        com.github.eco_heroes.proto.game_events.Unspecified, com.github.eco_heroes.proto.game_events.Unspecified.Builder, com.github.eco_heroes.proto.game_events.UnspecifiedOrBuilder> unspecifiedEvtBuilder_;
    /**
     * <code>.ecoheroes.Unspecified unspecifiedEvt = 1;</code>
     * @return Whether the unspecifiedEvt field is set.
     */
    @java.lang.Override
    public boolean hasUnspecifiedEvt() {
      return eventCase_ == 1;
    }
    /**
     * <code>.ecoheroes.Unspecified unspecifiedEvt = 1;</code>
     * @return The unspecifiedEvt.
     */
    @java.lang.Override
    public com.github.eco_heroes.proto.game_events.Unspecified getUnspecifiedEvt() {
      if (unspecifiedEvtBuilder_ == null) {
        if (eventCase_ == 1) {
          return (com.github.eco_heroes.proto.game_events.Unspecified) event_;
        }
        return com.github.eco_heroes.proto.game_events.Unspecified.getDefaultInstance();
      } else {
        if (eventCase_ == 1) {
          return unspecifiedEvtBuilder_.getMessage();
        }
        return com.github.eco_heroes.proto.game_events.Unspecified.getDefaultInstance();
      }
    }
    /**
     * <code>.ecoheroes.Unspecified unspecifiedEvt = 1;</code>
     */
    public Builder setUnspecifiedEvt(com.github.eco_heroes.proto.game_events.Unspecified value) {
      if (unspecifiedEvtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        unspecifiedEvtBuilder_.setMessage(value);
      }
      eventCase_ = 1;
      return this;
    }
    /**
     * <code>.ecoheroes.Unspecified unspecifiedEvt = 1;</code>
     */
    public Builder setUnspecifiedEvt(
        com.github.eco_heroes.proto.game_events.Unspecified.Builder builderForValue) {
      if (unspecifiedEvtBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        unspecifiedEvtBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 1;
      return this;
    }
    /**
     * <code>.ecoheroes.Unspecified unspecifiedEvt = 1;</code>
     */
    public Builder mergeUnspecifiedEvt(com.github.eco_heroes.proto.game_events.Unspecified value) {
      if (unspecifiedEvtBuilder_ == null) {
        if (eventCase_ == 1 &&
            event_ != com.github.eco_heroes.proto.game_events.Unspecified.getDefaultInstance()) {
          event_ = com.github.eco_heroes.proto.game_events.Unspecified.newBuilder((com.github.eco_heroes.proto.game_events.Unspecified) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 1) {
          unspecifiedEvtBuilder_.mergeFrom(value);
        } else {
          unspecifiedEvtBuilder_.setMessage(value);
        }
      }
      eventCase_ = 1;
      return this;
    }
    /**
     * <code>.ecoheroes.Unspecified unspecifiedEvt = 1;</code>
     */
    public Builder clearUnspecifiedEvt() {
      if (unspecifiedEvtBuilder_ == null) {
        if (eventCase_ == 1) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 1) {
          eventCase_ = 0;
          event_ = null;
        }
        unspecifiedEvtBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ecoheroes.Unspecified unspecifiedEvt = 1;</code>
     */
    public com.github.eco_heroes.proto.game_events.Unspecified.Builder getUnspecifiedEvtBuilder() {
      return getUnspecifiedEvtFieldBuilder().getBuilder();
    }
    /**
     * <code>.ecoheroes.Unspecified unspecifiedEvt = 1;</code>
     */
    @java.lang.Override
    public com.github.eco_heroes.proto.game_events.UnspecifiedOrBuilder getUnspecifiedEvtOrBuilder() {
      if ((eventCase_ == 1) && (unspecifiedEvtBuilder_ != null)) {
        return unspecifiedEvtBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 1) {
          return (com.github.eco_heroes.proto.game_events.Unspecified) event_;
        }
        return com.github.eco_heroes.proto.game_events.Unspecified.getDefaultInstance();
      }
    }
    /**
     * <code>.ecoheroes.Unspecified unspecifiedEvt = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.eco_heroes.proto.game_events.Unspecified, com.github.eco_heroes.proto.game_events.Unspecified.Builder, com.github.eco_heroes.proto.game_events.UnspecifiedOrBuilder> 
        getUnspecifiedEvtFieldBuilder() {
      if (unspecifiedEvtBuilder_ == null) {
        if (!(eventCase_ == 1)) {
          event_ = com.github.eco_heroes.proto.game_events.Unspecified.getDefaultInstance();
        }
        unspecifiedEvtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.eco_heroes.proto.game_events.Unspecified, com.github.eco_heroes.proto.game_events.Unspecified.Builder, com.github.eco_heroes.proto.game_events.UnspecifiedOrBuilder>(
                (com.github.eco_heroes.proto.game_events.Unspecified) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 1;
      onChanged();
      return unspecifiedEvtBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.github.eco_heroes.proto.game_events.PlayerAdded, com.github.eco_heroes.proto.game_events.PlayerAdded.Builder, com.github.eco_heroes.proto.game_events.PlayerAddedOrBuilder> playerAddedEvtBuilder_;
    /**
     * <code>.ecoheroes.PlayerAdded playerAddedEvt = 2;</code>
     * @return Whether the playerAddedEvt field is set.
     */
    @java.lang.Override
    public boolean hasPlayerAddedEvt() {
      return eventCase_ == 2;
    }
    /**
     * <code>.ecoheroes.PlayerAdded playerAddedEvt = 2;</code>
     * @return The playerAddedEvt.
     */
    @java.lang.Override
    public com.github.eco_heroes.proto.game_events.PlayerAdded getPlayerAddedEvt() {
      if (playerAddedEvtBuilder_ == null) {
        if (eventCase_ == 2) {
          return (com.github.eco_heroes.proto.game_events.PlayerAdded) event_;
        }
        return com.github.eco_heroes.proto.game_events.PlayerAdded.getDefaultInstance();
      } else {
        if (eventCase_ == 2) {
          return playerAddedEvtBuilder_.getMessage();
        }
        return com.github.eco_heroes.proto.game_events.PlayerAdded.getDefaultInstance();
      }
    }
    /**
     * <code>.ecoheroes.PlayerAdded playerAddedEvt = 2;</code>
     */
    public Builder setPlayerAddedEvt(com.github.eco_heroes.proto.game_events.PlayerAdded value) {
      if (playerAddedEvtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        playerAddedEvtBuilder_.setMessage(value);
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>.ecoheroes.PlayerAdded playerAddedEvt = 2;</code>
     */
    public Builder setPlayerAddedEvt(
        com.github.eco_heroes.proto.game_events.PlayerAdded.Builder builderForValue) {
      if (playerAddedEvtBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        playerAddedEvtBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>.ecoheroes.PlayerAdded playerAddedEvt = 2;</code>
     */
    public Builder mergePlayerAddedEvt(com.github.eco_heroes.proto.game_events.PlayerAdded value) {
      if (playerAddedEvtBuilder_ == null) {
        if (eventCase_ == 2 &&
            event_ != com.github.eco_heroes.proto.game_events.PlayerAdded.getDefaultInstance()) {
          event_ = com.github.eco_heroes.proto.game_events.PlayerAdded.newBuilder((com.github.eco_heroes.proto.game_events.PlayerAdded) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 2) {
          playerAddedEvtBuilder_.mergeFrom(value);
        } else {
          playerAddedEvtBuilder_.setMessage(value);
        }
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>.ecoheroes.PlayerAdded playerAddedEvt = 2;</code>
     */
    public Builder clearPlayerAddedEvt() {
      if (playerAddedEvtBuilder_ == null) {
        if (eventCase_ == 2) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 2) {
          eventCase_ = 0;
          event_ = null;
        }
        playerAddedEvtBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ecoheroes.PlayerAdded playerAddedEvt = 2;</code>
     */
    public com.github.eco_heroes.proto.game_events.PlayerAdded.Builder getPlayerAddedEvtBuilder() {
      return getPlayerAddedEvtFieldBuilder().getBuilder();
    }
    /**
     * <code>.ecoheroes.PlayerAdded playerAddedEvt = 2;</code>
     */
    @java.lang.Override
    public com.github.eco_heroes.proto.game_events.PlayerAddedOrBuilder getPlayerAddedEvtOrBuilder() {
      if ((eventCase_ == 2) && (playerAddedEvtBuilder_ != null)) {
        return playerAddedEvtBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 2) {
          return (com.github.eco_heroes.proto.game_events.PlayerAdded) event_;
        }
        return com.github.eco_heroes.proto.game_events.PlayerAdded.getDefaultInstance();
      }
    }
    /**
     * <code>.ecoheroes.PlayerAdded playerAddedEvt = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.eco_heroes.proto.game_events.PlayerAdded, com.github.eco_heroes.proto.game_events.PlayerAdded.Builder, com.github.eco_heroes.proto.game_events.PlayerAddedOrBuilder> 
        getPlayerAddedEvtFieldBuilder() {
      if (playerAddedEvtBuilder_ == null) {
        if (!(eventCase_ == 2)) {
          event_ = com.github.eco_heroes.proto.game_events.PlayerAdded.getDefaultInstance();
        }
        playerAddedEvtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.eco_heroes.proto.game_events.PlayerAdded, com.github.eco_heroes.proto.game_events.PlayerAdded.Builder, com.github.eco_heroes.proto.game_events.PlayerAddedOrBuilder>(
                (com.github.eco_heroes.proto.game_events.PlayerAdded) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 2;
      onChanged();
      return playerAddedEvtBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.github.eco_heroes.proto.game_events.PlayerRemoved, com.github.eco_heroes.proto.game_events.PlayerRemoved.Builder, com.github.eco_heroes.proto.game_events.PlayerRemovedOrBuilder> playerRemovedEvtBuilder_;
    /**
     * <code>.ecoheroes.PlayerRemoved playerRemovedEvt = 3;</code>
     * @return Whether the playerRemovedEvt field is set.
     */
    @java.lang.Override
    public boolean hasPlayerRemovedEvt() {
      return eventCase_ == 3;
    }
    /**
     * <code>.ecoheroes.PlayerRemoved playerRemovedEvt = 3;</code>
     * @return The playerRemovedEvt.
     */
    @java.lang.Override
    public com.github.eco_heroes.proto.game_events.PlayerRemoved getPlayerRemovedEvt() {
      if (playerRemovedEvtBuilder_ == null) {
        if (eventCase_ == 3) {
          return (com.github.eco_heroes.proto.game_events.PlayerRemoved) event_;
        }
        return com.github.eco_heroes.proto.game_events.PlayerRemoved.getDefaultInstance();
      } else {
        if (eventCase_ == 3) {
          return playerRemovedEvtBuilder_.getMessage();
        }
        return com.github.eco_heroes.proto.game_events.PlayerRemoved.getDefaultInstance();
      }
    }
    /**
     * <code>.ecoheroes.PlayerRemoved playerRemovedEvt = 3;</code>
     */
    public Builder setPlayerRemovedEvt(com.github.eco_heroes.proto.game_events.PlayerRemoved value) {
      if (playerRemovedEvtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        playerRemovedEvtBuilder_.setMessage(value);
      }
      eventCase_ = 3;
      return this;
    }
    /**
     * <code>.ecoheroes.PlayerRemoved playerRemovedEvt = 3;</code>
     */
    public Builder setPlayerRemovedEvt(
        com.github.eco_heroes.proto.game_events.PlayerRemoved.Builder builderForValue) {
      if (playerRemovedEvtBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        playerRemovedEvtBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 3;
      return this;
    }
    /**
     * <code>.ecoheroes.PlayerRemoved playerRemovedEvt = 3;</code>
     */
    public Builder mergePlayerRemovedEvt(com.github.eco_heroes.proto.game_events.PlayerRemoved value) {
      if (playerRemovedEvtBuilder_ == null) {
        if (eventCase_ == 3 &&
            event_ != com.github.eco_heroes.proto.game_events.PlayerRemoved.getDefaultInstance()) {
          event_ = com.github.eco_heroes.proto.game_events.PlayerRemoved.newBuilder((com.github.eco_heroes.proto.game_events.PlayerRemoved) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 3) {
          playerRemovedEvtBuilder_.mergeFrom(value);
        } else {
          playerRemovedEvtBuilder_.setMessage(value);
        }
      }
      eventCase_ = 3;
      return this;
    }
    /**
     * <code>.ecoheroes.PlayerRemoved playerRemovedEvt = 3;</code>
     */
    public Builder clearPlayerRemovedEvt() {
      if (playerRemovedEvtBuilder_ == null) {
        if (eventCase_ == 3) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 3) {
          eventCase_ = 0;
          event_ = null;
        }
        playerRemovedEvtBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ecoheroes.PlayerRemoved playerRemovedEvt = 3;</code>
     */
    public com.github.eco_heroes.proto.game_events.PlayerRemoved.Builder getPlayerRemovedEvtBuilder() {
      return getPlayerRemovedEvtFieldBuilder().getBuilder();
    }
    /**
     * <code>.ecoheroes.PlayerRemoved playerRemovedEvt = 3;</code>
     */
    @java.lang.Override
    public com.github.eco_heroes.proto.game_events.PlayerRemovedOrBuilder getPlayerRemovedEvtOrBuilder() {
      if ((eventCase_ == 3) && (playerRemovedEvtBuilder_ != null)) {
        return playerRemovedEvtBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 3) {
          return (com.github.eco_heroes.proto.game_events.PlayerRemoved) event_;
        }
        return com.github.eco_heroes.proto.game_events.PlayerRemoved.getDefaultInstance();
      }
    }
    /**
     * <code>.ecoheroes.PlayerRemoved playerRemovedEvt = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.eco_heroes.proto.game_events.PlayerRemoved, com.github.eco_heroes.proto.game_events.PlayerRemoved.Builder, com.github.eco_heroes.proto.game_events.PlayerRemovedOrBuilder> 
        getPlayerRemovedEvtFieldBuilder() {
      if (playerRemovedEvtBuilder_ == null) {
        if (!(eventCase_ == 3)) {
          event_ = com.github.eco_heroes.proto.game_events.PlayerRemoved.getDefaultInstance();
        }
        playerRemovedEvtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.eco_heroes.proto.game_events.PlayerRemoved, com.github.eco_heroes.proto.game_events.PlayerRemoved.Builder, com.github.eco_heroes.proto.game_events.PlayerRemovedOrBuilder>(
                (com.github.eco_heroes.proto.game_events.PlayerRemoved) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 3;
      onChanged();
      return playerRemovedEvtBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.github.eco_heroes.proto.game_events.GameStarted, com.github.eco_heroes.proto.game_events.GameStarted.Builder, com.github.eco_heroes.proto.game_events.GameStartedOrBuilder> gameStartedEvtBuilder_;
    /**
     * <code>.ecoheroes.GameStarted gameStartedEvt = 4;</code>
     * @return Whether the gameStartedEvt field is set.
     */
    @java.lang.Override
    public boolean hasGameStartedEvt() {
      return eventCase_ == 4;
    }
    /**
     * <code>.ecoheroes.GameStarted gameStartedEvt = 4;</code>
     * @return The gameStartedEvt.
     */
    @java.lang.Override
    public com.github.eco_heroes.proto.game_events.GameStarted getGameStartedEvt() {
      if (gameStartedEvtBuilder_ == null) {
        if (eventCase_ == 4) {
          return (com.github.eco_heroes.proto.game_events.GameStarted) event_;
        }
        return com.github.eco_heroes.proto.game_events.GameStarted.getDefaultInstance();
      } else {
        if (eventCase_ == 4) {
          return gameStartedEvtBuilder_.getMessage();
        }
        return com.github.eco_heroes.proto.game_events.GameStarted.getDefaultInstance();
      }
    }
    /**
     * <code>.ecoheroes.GameStarted gameStartedEvt = 4;</code>
     */
    public Builder setGameStartedEvt(com.github.eco_heroes.proto.game_events.GameStarted value) {
      if (gameStartedEvtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        gameStartedEvtBuilder_.setMessage(value);
      }
      eventCase_ = 4;
      return this;
    }
    /**
     * <code>.ecoheroes.GameStarted gameStartedEvt = 4;</code>
     */
    public Builder setGameStartedEvt(
        com.github.eco_heroes.proto.game_events.GameStarted.Builder builderForValue) {
      if (gameStartedEvtBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        gameStartedEvtBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 4;
      return this;
    }
    /**
     * <code>.ecoheroes.GameStarted gameStartedEvt = 4;</code>
     */
    public Builder mergeGameStartedEvt(com.github.eco_heroes.proto.game_events.GameStarted value) {
      if (gameStartedEvtBuilder_ == null) {
        if (eventCase_ == 4 &&
            event_ != com.github.eco_heroes.proto.game_events.GameStarted.getDefaultInstance()) {
          event_ = com.github.eco_heroes.proto.game_events.GameStarted.newBuilder((com.github.eco_heroes.proto.game_events.GameStarted) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 4) {
          gameStartedEvtBuilder_.mergeFrom(value);
        } else {
          gameStartedEvtBuilder_.setMessage(value);
        }
      }
      eventCase_ = 4;
      return this;
    }
    /**
     * <code>.ecoheroes.GameStarted gameStartedEvt = 4;</code>
     */
    public Builder clearGameStartedEvt() {
      if (gameStartedEvtBuilder_ == null) {
        if (eventCase_ == 4) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 4) {
          eventCase_ = 0;
          event_ = null;
        }
        gameStartedEvtBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ecoheroes.GameStarted gameStartedEvt = 4;</code>
     */
    public com.github.eco_heroes.proto.game_events.GameStarted.Builder getGameStartedEvtBuilder() {
      return getGameStartedEvtFieldBuilder().getBuilder();
    }
    /**
     * <code>.ecoheroes.GameStarted gameStartedEvt = 4;</code>
     */
    @java.lang.Override
    public com.github.eco_heroes.proto.game_events.GameStartedOrBuilder getGameStartedEvtOrBuilder() {
      if ((eventCase_ == 4) && (gameStartedEvtBuilder_ != null)) {
        return gameStartedEvtBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 4) {
          return (com.github.eco_heroes.proto.game_events.GameStarted) event_;
        }
        return com.github.eco_heroes.proto.game_events.GameStarted.getDefaultInstance();
      }
    }
    /**
     * <code>.ecoheroes.GameStarted gameStartedEvt = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.eco_heroes.proto.game_events.GameStarted, com.github.eco_heroes.proto.game_events.GameStarted.Builder, com.github.eco_heroes.proto.game_events.GameStartedOrBuilder> 
        getGameStartedEvtFieldBuilder() {
      if (gameStartedEvtBuilder_ == null) {
        if (!(eventCase_ == 4)) {
          event_ = com.github.eco_heroes.proto.game_events.GameStarted.getDefaultInstance();
        }
        gameStartedEvtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.eco_heroes.proto.game_events.GameStarted, com.github.eco_heroes.proto.game_events.GameStarted.Builder, com.github.eco_heroes.proto.game_events.GameStartedOrBuilder>(
                (com.github.eco_heroes.proto.game_events.GameStarted) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 4;
      onChanged();
      return gameStartedEvtBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.github.eco_heroes.proto.game_events.WasteGenerated, com.github.eco_heroes.proto.game_events.WasteGenerated.Builder, com.github.eco_heroes.proto.game_events.WasteGeneratedOrBuilder> wasteGeneratedEvtBuilder_;
    /**
     * <code>.ecoheroes.WasteGenerated wasteGeneratedEvt = 5;</code>
     * @return Whether the wasteGeneratedEvt field is set.
     */
    @java.lang.Override
    public boolean hasWasteGeneratedEvt() {
      return eventCase_ == 5;
    }
    /**
     * <code>.ecoheroes.WasteGenerated wasteGeneratedEvt = 5;</code>
     * @return The wasteGeneratedEvt.
     */
    @java.lang.Override
    public com.github.eco_heroes.proto.game_events.WasteGenerated getWasteGeneratedEvt() {
      if (wasteGeneratedEvtBuilder_ == null) {
        if (eventCase_ == 5) {
          return (com.github.eco_heroes.proto.game_events.WasteGenerated) event_;
        }
        return com.github.eco_heroes.proto.game_events.WasteGenerated.getDefaultInstance();
      } else {
        if (eventCase_ == 5) {
          return wasteGeneratedEvtBuilder_.getMessage();
        }
        return com.github.eco_heroes.proto.game_events.WasteGenerated.getDefaultInstance();
      }
    }
    /**
     * <code>.ecoheroes.WasteGenerated wasteGeneratedEvt = 5;</code>
     */
    public Builder setWasteGeneratedEvt(com.github.eco_heroes.proto.game_events.WasteGenerated value) {
      if (wasteGeneratedEvtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        wasteGeneratedEvtBuilder_.setMessage(value);
      }
      eventCase_ = 5;
      return this;
    }
    /**
     * <code>.ecoheroes.WasteGenerated wasteGeneratedEvt = 5;</code>
     */
    public Builder setWasteGeneratedEvt(
        com.github.eco_heroes.proto.game_events.WasteGenerated.Builder builderForValue) {
      if (wasteGeneratedEvtBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        wasteGeneratedEvtBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 5;
      return this;
    }
    /**
     * <code>.ecoheroes.WasteGenerated wasteGeneratedEvt = 5;</code>
     */
    public Builder mergeWasteGeneratedEvt(com.github.eco_heroes.proto.game_events.WasteGenerated value) {
      if (wasteGeneratedEvtBuilder_ == null) {
        if (eventCase_ == 5 &&
            event_ != com.github.eco_heroes.proto.game_events.WasteGenerated.getDefaultInstance()) {
          event_ = com.github.eco_heroes.proto.game_events.WasteGenerated.newBuilder((com.github.eco_heroes.proto.game_events.WasteGenerated) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 5) {
          wasteGeneratedEvtBuilder_.mergeFrom(value);
        } else {
          wasteGeneratedEvtBuilder_.setMessage(value);
        }
      }
      eventCase_ = 5;
      return this;
    }
    /**
     * <code>.ecoheroes.WasteGenerated wasteGeneratedEvt = 5;</code>
     */
    public Builder clearWasteGeneratedEvt() {
      if (wasteGeneratedEvtBuilder_ == null) {
        if (eventCase_ == 5) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 5) {
          eventCase_ = 0;
          event_ = null;
        }
        wasteGeneratedEvtBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ecoheroes.WasteGenerated wasteGeneratedEvt = 5;</code>
     */
    public com.github.eco_heroes.proto.game_events.WasteGenerated.Builder getWasteGeneratedEvtBuilder() {
      return getWasteGeneratedEvtFieldBuilder().getBuilder();
    }
    /**
     * <code>.ecoheroes.WasteGenerated wasteGeneratedEvt = 5;</code>
     */
    @java.lang.Override
    public com.github.eco_heroes.proto.game_events.WasteGeneratedOrBuilder getWasteGeneratedEvtOrBuilder() {
      if ((eventCase_ == 5) && (wasteGeneratedEvtBuilder_ != null)) {
        return wasteGeneratedEvtBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 5) {
          return (com.github.eco_heroes.proto.game_events.WasteGenerated) event_;
        }
        return com.github.eco_heroes.proto.game_events.WasteGenerated.getDefaultInstance();
      }
    }
    /**
     * <code>.ecoheroes.WasteGenerated wasteGeneratedEvt = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.eco_heroes.proto.game_events.WasteGenerated, com.github.eco_heroes.proto.game_events.WasteGenerated.Builder, com.github.eco_heroes.proto.game_events.WasteGeneratedOrBuilder> 
        getWasteGeneratedEvtFieldBuilder() {
      if (wasteGeneratedEvtBuilder_ == null) {
        if (!(eventCase_ == 5)) {
          event_ = com.github.eco_heroes.proto.game_events.WasteGenerated.getDefaultInstance();
        }
        wasteGeneratedEvtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.eco_heroes.proto.game_events.WasteGenerated, com.github.eco_heroes.proto.game_events.WasteGenerated.Builder, com.github.eco_heroes.proto.game_events.WasteGeneratedOrBuilder>(
                (com.github.eco_heroes.proto.game_events.WasteGenerated) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 5;
      onChanged();
      return wasteGeneratedEvtBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.github.eco_heroes.proto.game_events.LifeLost, com.github.eco_heroes.proto.game_events.LifeLost.Builder, com.github.eco_heroes.proto.game_events.LifeLostOrBuilder> lifeLostEvtBuilder_;
    /**
     * <code>.ecoheroes.LifeLost lifeLostEvt = 6;</code>
     * @return Whether the lifeLostEvt field is set.
     */
    @java.lang.Override
    public boolean hasLifeLostEvt() {
      return eventCase_ == 6;
    }
    /**
     * <code>.ecoheroes.LifeLost lifeLostEvt = 6;</code>
     * @return The lifeLostEvt.
     */
    @java.lang.Override
    public com.github.eco_heroes.proto.game_events.LifeLost getLifeLostEvt() {
      if (lifeLostEvtBuilder_ == null) {
        if (eventCase_ == 6) {
          return (com.github.eco_heroes.proto.game_events.LifeLost) event_;
        }
        return com.github.eco_heroes.proto.game_events.LifeLost.getDefaultInstance();
      } else {
        if (eventCase_ == 6) {
          return lifeLostEvtBuilder_.getMessage();
        }
        return com.github.eco_heroes.proto.game_events.LifeLost.getDefaultInstance();
      }
    }
    /**
     * <code>.ecoheroes.LifeLost lifeLostEvt = 6;</code>
     */
    public Builder setLifeLostEvt(com.github.eco_heroes.proto.game_events.LifeLost value) {
      if (lifeLostEvtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        lifeLostEvtBuilder_.setMessage(value);
      }
      eventCase_ = 6;
      return this;
    }
    /**
     * <code>.ecoheroes.LifeLost lifeLostEvt = 6;</code>
     */
    public Builder setLifeLostEvt(
        com.github.eco_heroes.proto.game_events.LifeLost.Builder builderForValue) {
      if (lifeLostEvtBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        lifeLostEvtBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 6;
      return this;
    }
    /**
     * <code>.ecoheroes.LifeLost lifeLostEvt = 6;</code>
     */
    public Builder mergeLifeLostEvt(com.github.eco_heroes.proto.game_events.LifeLost value) {
      if (lifeLostEvtBuilder_ == null) {
        if (eventCase_ == 6 &&
            event_ != com.github.eco_heroes.proto.game_events.LifeLost.getDefaultInstance()) {
          event_ = com.github.eco_heroes.proto.game_events.LifeLost.newBuilder((com.github.eco_heroes.proto.game_events.LifeLost) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 6) {
          lifeLostEvtBuilder_.mergeFrom(value);
        } else {
          lifeLostEvtBuilder_.setMessage(value);
        }
      }
      eventCase_ = 6;
      return this;
    }
    /**
     * <code>.ecoheroes.LifeLost lifeLostEvt = 6;</code>
     */
    public Builder clearLifeLostEvt() {
      if (lifeLostEvtBuilder_ == null) {
        if (eventCase_ == 6) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 6) {
          eventCase_ = 0;
          event_ = null;
        }
        lifeLostEvtBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ecoheroes.LifeLost lifeLostEvt = 6;</code>
     */
    public com.github.eco_heroes.proto.game_events.LifeLost.Builder getLifeLostEvtBuilder() {
      return getLifeLostEvtFieldBuilder().getBuilder();
    }
    /**
     * <code>.ecoheroes.LifeLost lifeLostEvt = 6;</code>
     */
    @java.lang.Override
    public com.github.eco_heroes.proto.game_events.LifeLostOrBuilder getLifeLostEvtOrBuilder() {
      if ((eventCase_ == 6) && (lifeLostEvtBuilder_ != null)) {
        return lifeLostEvtBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 6) {
          return (com.github.eco_heroes.proto.game_events.LifeLost) event_;
        }
        return com.github.eco_heroes.proto.game_events.LifeLost.getDefaultInstance();
      }
    }
    /**
     * <code>.ecoheroes.LifeLost lifeLostEvt = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.eco_heroes.proto.game_events.LifeLost, com.github.eco_heroes.proto.game_events.LifeLost.Builder, com.github.eco_heroes.proto.game_events.LifeLostOrBuilder> 
        getLifeLostEvtFieldBuilder() {
      if (lifeLostEvtBuilder_ == null) {
        if (!(eventCase_ == 6)) {
          event_ = com.github.eco_heroes.proto.game_events.LifeLost.getDefaultInstance();
        }
        lifeLostEvtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.eco_heroes.proto.game_events.LifeLost, com.github.eco_heroes.proto.game_events.LifeLost.Builder, com.github.eco_heroes.proto.game_events.LifeLostOrBuilder>(
                (com.github.eco_heroes.proto.game_events.LifeLost) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 6;
      onChanged();
      return lifeLostEvtBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.github.eco_heroes.proto.game_events.SpeedIncreased, com.github.eco_heroes.proto.game_events.SpeedIncreased.Builder, com.github.eco_heroes.proto.game_events.SpeedIncreasedOrBuilder> speedIncreasedEvtBuilder_;
    /**
     * <code>.ecoheroes.SpeedIncreased speedIncreasedEvt = 7;</code>
     * @return Whether the speedIncreasedEvt field is set.
     */
    @java.lang.Override
    public boolean hasSpeedIncreasedEvt() {
      return eventCase_ == 7;
    }
    /**
     * <code>.ecoheroes.SpeedIncreased speedIncreasedEvt = 7;</code>
     * @return The speedIncreasedEvt.
     */
    @java.lang.Override
    public com.github.eco_heroes.proto.game_events.SpeedIncreased getSpeedIncreasedEvt() {
      if (speedIncreasedEvtBuilder_ == null) {
        if (eventCase_ == 7) {
          return (com.github.eco_heroes.proto.game_events.SpeedIncreased) event_;
        }
        return com.github.eco_heroes.proto.game_events.SpeedIncreased.getDefaultInstance();
      } else {
        if (eventCase_ == 7) {
          return speedIncreasedEvtBuilder_.getMessage();
        }
        return com.github.eco_heroes.proto.game_events.SpeedIncreased.getDefaultInstance();
      }
    }
    /**
     * <code>.ecoheroes.SpeedIncreased speedIncreasedEvt = 7;</code>
     */
    public Builder setSpeedIncreasedEvt(com.github.eco_heroes.proto.game_events.SpeedIncreased value) {
      if (speedIncreasedEvtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        speedIncreasedEvtBuilder_.setMessage(value);
      }
      eventCase_ = 7;
      return this;
    }
    /**
     * <code>.ecoheroes.SpeedIncreased speedIncreasedEvt = 7;</code>
     */
    public Builder setSpeedIncreasedEvt(
        com.github.eco_heroes.proto.game_events.SpeedIncreased.Builder builderForValue) {
      if (speedIncreasedEvtBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        speedIncreasedEvtBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 7;
      return this;
    }
    /**
     * <code>.ecoheroes.SpeedIncreased speedIncreasedEvt = 7;</code>
     */
    public Builder mergeSpeedIncreasedEvt(com.github.eco_heroes.proto.game_events.SpeedIncreased value) {
      if (speedIncreasedEvtBuilder_ == null) {
        if (eventCase_ == 7 &&
            event_ != com.github.eco_heroes.proto.game_events.SpeedIncreased.getDefaultInstance()) {
          event_ = com.github.eco_heroes.proto.game_events.SpeedIncreased.newBuilder((com.github.eco_heroes.proto.game_events.SpeedIncreased) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 7) {
          speedIncreasedEvtBuilder_.mergeFrom(value);
        } else {
          speedIncreasedEvtBuilder_.setMessage(value);
        }
      }
      eventCase_ = 7;
      return this;
    }
    /**
     * <code>.ecoheroes.SpeedIncreased speedIncreasedEvt = 7;</code>
     */
    public Builder clearSpeedIncreasedEvt() {
      if (speedIncreasedEvtBuilder_ == null) {
        if (eventCase_ == 7) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 7) {
          eventCase_ = 0;
          event_ = null;
        }
        speedIncreasedEvtBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ecoheroes.SpeedIncreased speedIncreasedEvt = 7;</code>
     */
    public com.github.eco_heroes.proto.game_events.SpeedIncreased.Builder getSpeedIncreasedEvtBuilder() {
      return getSpeedIncreasedEvtFieldBuilder().getBuilder();
    }
    /**
     * <code>.ecoheroes.SpeedIncreased speedIncreasedEvt = 7;</code>
     */
    @java.lang.Override
    public com.github.eco_heroes.proto.game_events.SpeedIncreasedOrBuilder getSpeedIncreasedEvtOrBuilder() {
      if ((eventCase_ == 7) && (speedIncreasedEvtBuilder_ != null)) {
        return speedIncreasedEvtBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 7) {
          return (com.github.eco_heroes.proto.game_events.SpeedIncreased) event_;
        }
        return com.github.eco_heroes.proto.game_events.SpeedIncreased.getDefaultInstance();
      }
    }
    /**
     * <code>.ecoheroes.SpeedIncreased speedIncreasedEvt = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.eco_heroes.proto.game_events.SpeedIncreased, com.github.eco_heroes.proto.game_events.SpeedIncreased.Builder, com.github.eco_heroes.proto.game_events.SpeedIncreasedOrBuilder> 
        getSpeedIncreasedEvtFieldBuilder() {
      if (speedIncreasedEvtBuilder_ == null) {
        if (!(eventCase_ == 7)) {
          event_ = com.github.eco_heroes.proto.game_events.SpeedIncreased.getDefaultInstance();
        }
        speedIncreasedEvtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.eco_heroes.proto.game_events.SpeedIncreased, com.github.eco_heroes.proto.game_events.SpeedIncreased.Builder, com.github.eco_heroes.proto.game_events.SpeedIncreasedOrBuilder>(
                (com.github.eco_heroes.proto.game_events.SpeedIncreased) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 7;
      onChanged();
      return speedIncreasedEvtBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.github.eco_heroes.proto.game_events.GameEnded, com.github.eco_heroes.proto.game_events.GameEnded.Builder, com.github.eco_heroes.proto.game_events.GameEndedOrBuilder> gameEndedEvtBuilder_;
    /**
     * <code>.ecoheroes.GameEnded gameEndedEvt = 8;</code>
     * @return Whether the gameEndedEvt field is set.
     */
    @java.lang.Override
    public boolean hasGameEndedEvt() {
      return eventCase_ == 8;
    }
    /**
     * <code>.ecoheroes.GameEnded gameEndedEvt = 8;</code>
     * @return The gameEndedEvt.
     */
    @java.lang.Override
    public com.github.eco_heroes.proto.game_events.GameEnded getGameEndedEvt() {
      if (gameEndedEvtBuilder_ == null) {
        if (eventCase_ == 8) {
          return (com.github.eco_heroes.proto.game_events.GameEnded) event_;
        }
        return com.github.eco_heroes.proto.game_events.GameEnded.getDefaultInstance();
      } else {
        if (eventCase_ == 8) {
          return gameEndedEvtBuilder_.getMessage();
        }
        return com.github.eco_heroes.proto.game_events.GameEnded.getDefaultInstance();
      }
    }
    /**
     * <code>.ecoheroes.GameEnded gameEndedEvt = 8;</code>
     */
    public Builder setGameEndedEvt(com.github.eco_heroes.proto.game_events.GameEnded value) {
      if (gameEndedEvtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        gameEndedEvtBuilder_.setMessage(value);
      }
      eventCase_ = 8;
      return this;
    }
    /**
     * <code>.ecoheroes.GameEnded gameEndedEvt = 8;</code>
     */
    public Builder setGameEndedEvt(
        com.github.eco_heroes.proto.game_events.GameEnded.Builder builderForValue) {
      if (gameEndedEvtBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        gameEndedEvtBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 8;
      return this;
    }
    /**
     * <code>.ecoheroes.GameEnded gameEndedEvt = 8;</code>
     */
    public Builder mergeGameEndedEvt(com.github.eco_heroes.proto.game_events.GameEnded value) {
      if (gameEndedEvtBuilder_ == null) {
        if (eventCase_ == 8 &&
            event_ != com.github.eco_heroes.proto.game_events.GameEnded.getDefaultInstance()) {
          event_ = com.github.eco_heroes.proto.game_events.GameEnded.newBuilder((com.github.eco_heroes.proto.game_events.GameEnded) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 8) {
          gameEndedEvtBuilder_.mergeFrom(value);
        } else {
          gameEndedEvtBuilder_.setMessage(value);
        }
      }
      eventCase_ = 8;
      return this;
    }
    /**
     * <code>.ecoheroes.GameEnded gameEndedEvt = 8;</code>
     */
    public Builder clearGameEndedEvt() {
      if (gameEndedEvtBuilder_ == null) {
        if (eventCase_ == 8) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 8) {
          eventCase_ = 0;
          event_ = null;
        }
        gameEndedEvtBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ecoheroes.GameEnded gameEndedEvt = 8;</code>
     */
    public com.github.eco_heroes.proto.game_events.GameEnded.Builder getGameEndedEvtBuilder() {
      return getGameEndedEvtFieldBuilder().getBuilder();
    }
    /**
     * <code>.ecoheroes.GameEnded gameEndedEvt = 8;</code>
     */
    @java.lang.Override
    public com.github.eco_heroes.proto.game_events.GameEndedOrBuilder getGameEndedEvtOrBuilder() {
      if ((eventCase_ == 8) && (gameEndedEvtBuilder_ != null)) {
        return gameEndedEvtBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 8) {
          return (com.github.eco_heroes.proto.game_events.GameEnded) event_;
        }
        return com.github.eco_heroes.proto.game_events.GameEnded.getDefaultInstance();
      }
    }
    /**
     * <code>.ecoheroes.GameEnded gameEndedEvt = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.eco_heroes.proto.game_events.GameEnded, com.github.eco_heroes.proto.game_events.GameEnded.Builder, com.github.eco_heroes.proto.game_events.GameEndedOrBuilder> 
        getGameEndedEvtFieldBuilder() {
      if (gameEndedEvtBuilder_ == null) {
        if (!(eventCase_ == 8)) {
          event_ = com.github.eco_heroes.proto.game_events.GameEnded.getDefaultInstance();
        }
        gameEndedEvtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.eco_heroes.proto.game_events.GameEnded, com.github.eco_heroes.proto.game_events.GameEnded.Builder, com.github.eco_heroes.proto.game_events.GameEndedOrBuilder>(
                (com.github.eco_heroes.proto.game_events.GameEnded) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 8;
      onChanged();
      return gameEndedEvtBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:ecoheroes.ServerEvent)
  }

  // @@protoc_insertion_point(class_scope:ecoheroes.ServerEvent)
  private static final com.github.eco_heroes.proto.game_events.ServerEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.eco_heroes.proto.game_events.ServerEvent();
  }

  public static com.github.eco_heroes.proto.game_events.ServerEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServerEvent>
      PARSER = new com.google.protobuf.AbstractParser<ServerEvent>() {
    @java.lang.Override
    public ServerEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ServerEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServerEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.eco_heroes.proto.game_events.ServerEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

