// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: game-events.proto
// Protobuf Java Version: 4.28.3

package com.github.eco_heroes.proto.game_events;

public interface ServerEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ecoheroes.ServerEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ecoheroes.Unspecified unspecifiedEvt = 1;</code>
   * @return Whether the unspecifiedEvt field is set.
   */
  boolean hasUnspecifiedEvt();
  /**
   * <code>.ecoheroes.Unspecified unspecifiedEvt = 1;</code>
   * @return The unspecifiedEvt.
   */
  com.github.eco_heroes.proto.game_events.Unspecified getUnspecifiedEvt();
  /**
   * <code>.ecoheroes.Unspecified unspecifiedEvt = 1;</code>
   */
  com.github.eco_heroes.proto.game_events.UnspecifiedOrBuilder getUnspecifiedEvtOrBuilder();

  /**
   * <code>.ecoheroes.PlayerAdded playerAddedEvt = 2;</code>
   * @return Whether the playerAddedEvt field is set.
   */
  boolean hasPlayerAddedEvt();
  /**
   * <code>.ecoheroes.PlayerAdded playerAddedEvt = 2;</code>
   * @return The playerAddedEvt.
   */
  com.github.eco_heroes.proto.game_events.PlayerAdded getPlayerAddedEvt();
  /**
   * <code>.ecoheroes.PlayerAdded playerAddedEvt = 2;</code>
   */
  com.github.eco_heroes.proto.game_events.PlayerAddedOrBuilder getPlayerAddedEvtOrBuilder();

  /**
   * <code>.ecoheroes.PlayerRemoved playerRemovedEvt = 3;</code>
   * @return Whether the playerRemovedEvt field is set.
   */
  boolean hasPlayerRemovedEvt();
  /**
   * <code>.ecoheroes.PlayerRemoved playerRemovedEvt = 3;</code>
   * @return The playerRemovedEvt.
   */
  com.github.eco_heroes.proto.game_events.PlayerRemoved getPlayerRemovedEvt();
  /**
   * <code>.ecoheroes.PlayerRemoved playerRemovedEvt = 3;</code>
   */
  com.github.eco_heroes.proto.game_events.PlayerRemovedOrBuilder getPlayerRemovedEvtOrBuilder();

  /**
   * <code>.ecoheroes.GameStarted gameStartedEvt = 4;</code>
   * @return Whether the gameStartedEvt field is set.
   */
  boolean hasGameStartedEvt();
  /**
   * <code>.ecoheroes.GameStarted gameStartedEvt = 4;</code>
   * @return The gameStartedEvt.
   */
  com.github.eco_heroes.proto.game_events.GameStarted getGameStartedEvt();
  /**
   * <code>.ecoheroes.GameStarted gameStartedEvt = 4;</code>
   */
  com.github.eco_heroes.proto.game_events.GameStartedOrBuilder getGameStartedEvtOrBuilder();

  /**
   * <code>.ecoheroes.WasteGenerated wasteGeneratedEvt = 5;</code>
   * @return Whether the wasteGeneratedEvt field is set.
   */
  boolean hasWasteGeneratedEvt();
  /**
   * <code>.ecoheroes.WasteGenerated wasteGeneratedEvt = 5;</code>
   * @return The wasteGeneratedEvt.
   */
  com.github.eco_heroes.proto.game_events.WasteGenerated getWasteGeneratedEvt();
  /**
   * <code>.ecoheroes.WasteGenerated wasteGeneratedEvt = 5;</code>
   */
  com.github.eco_heroes.proto.game_events.WasteGeneratedOrBuilder getWasteGeneratedEvtOrBuilder();

  /**
   * <code>.ecoheroes.LifeLost lifeLostEvt = 6;</code>
   * @return Whether the lifeLostEvt field is set.
   */
  boolean hasLifeLostEvt();
  /**
   * <code>.ecoheroes.LifeLost lifeLostEvt = 6;</code>
   * @return The lifeLostEvt.
   */
  com.github.eco_heroes.proto.game_events.LifeLost getLifeLostEvt();
  /**
   * <code>.ecoheroes.LifeLost lifeLostEvt = 6;</code>
   */
  com.github.eco_heroes.proto.game_events.LifeLostOrBuilder getLifeLostEvtOrBuilder();

  /**
   * <code>.ecoheroes.SpeedIncreased speedIncreasedEvt = 7;</code>
   * @return Whether the speedIncreasedEvt field is set.
   */
  boolean hasSpeedIncreasedEvt();
  /**
   * <code>.ecoheroes.SpeedIncreased speedIncreasedEvt = 7;</code>
   * @return The speedIncreasedEvt.
   */
  com.github.eco_heroes.proto.game_events.SpeedIncreased getSpeedIncreasedEvt();
  /**
   * <code>.ecoheroes.SpeedIncreased speedIncreasedEvt = 7;</code>
   */
  com.github.eco_heroes.proto.game_events.SpeedIncreasedOrBuilder getSpeedIncreasedEvtOrBuilder();

  /**
   * <code>.ecoheroes.GameEnded gameEndedEvt = 8;</code>
   * @return Whether the gameEndedEvt field is set.
   */
  boolean hasGameEndedEvt();
  /**
   * <code>.ecoheroes.GameEnded gameEndedEvt = 8;</code>
   * @return The gameEndedEvt.
   */
  com.github.eco_heroes.proto.game_events.GameEnded getGameEndedEvt();
  /**
   * <code>.ecoheroes.GameEnded gameEndedEvt = 8;</code>
   */
  com.github.eco_heroes.proto.game_events.GameEndedOrBuilder getGameEndedEvtOrBuilder();

  com.github.eco_heroes.proto.game_events.ServerEvent.EventCase getEventCase();
}
