// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: game-events.proto
// Protobuf Java Version: 4.28.2

package com.github.eco_heroes.proto.game_events;

public interface SpeedIncreasedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ecoheroes.SpeedIncreased)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 speed = 1;</code>
   * @return The speed.
   */
  int getSpeed();
}
