// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: game-events.proto
// Protobuf Java Version: 4.28.2

package com.github.eco_heroes.proto.game_events;

public interface SubscriptionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ecoheroes.SubscriptionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string roomId = 1;</code>
   * @return The roomId.
   */
  java.lang.String getRoomId();
  /**
   * <code>string roomId = 1;</code>
   * @return The bytes for roomId.
   */
  com.google.protobuf.ByteString
      getRoomIdBytes();
}
