// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: game-events.proto
// Protobuf Java Version: 4.28.2

package com.github.eco_heroes.proto.game_events;

public interface UnspecifiedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ecoheroes.Unspecified)
    com.google.protobuf.MessageOrBuilder {
}
