// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: game-events.proto
// Protobuf Java Version: 4.28.3

package com.github.eco_heroes.proto.game_events;

/**
 * Protobuf enum {@code ecoheroes.WasteType}
 */
public enum WasteType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>PLASTIC_BOTTLE = 0;</code>
   */
  PLASTIC_BOTTLE(0),
  /**
   * <code>PLASTIC_JUG = 1;</code>
   */
  PLASTIC_JUG(1),
  /**
   * <code>PLASTIC_DETERGENT_BOTTLE = 2;</code>
   */
  PLASTIC_DETERGENT_BOTTLE(2),
  /**
   * <code>PAPER_NEWSPAPER = 3;</code>
   */
  PAPER_NEWSPAPER(3),
  /**
   * <code>PAPER_BAG = 4;</code>
   */
  PAPER_BAG(4),
  /**
   * <code>GLASS_SODA_BOTTLE = 5;</code>
   */
  GLASS_SODA_BOTTLE(5),
  /**
   * <code>GLASS_JAR = 6;</code>
   */
  GLASS_JAR(6),
  /**
   * <code>GLASS_BOTTLE = 7;</code>
   */
  GLASS_BOTTLE(7),
  /**
   * <code>METAL_SMALL_CAN = 8;</code>
   */
  METAL_SMALL_CAN(8),
  /**
   * <code>METAL_CAN = 9;</code>
   */
  METAL_CAN(9),
  /**
   * <code>METAL_SODA_CAN = 10;</code>
   */
  METAL_SODA_CAN(10),
  /**
   * <code>POLYSTYRENE_CUP = 11;</code>
   */
  POLYSTYRENE_CUP(11),
  /**
   * <code>PIZZA_BOX = 12;</code>
   */
  PIZZA_BOX(12),
  /**
   * <code>MUG = 13;</code>
   */
  MUG(13),
  /**
   * <code>AEROSOL_CAN = 14;</code>
   */
  AEROSOL_CAN(14),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      WasteType.class.getName());
  }
  /**
   * <code>PLASTIC_BOTTLE = 0;</code>
   */
  public static final int PLASTIC_BOTTLE_VALUE = 0;
  /**
   * <code>PLASTIC_JUG = 1;</code>
   */
  public static final int PLASTIC_JUG_VALUE = 1;
  /**
   * <code>PLASTIC_DETERGENT_BOTTLE = 2;</code>
   */
  public static final int PLASTIC_DETERGENT_BOTTLE_VALUE = 2;
  /**
   * <code>PAPER_NEWSPAPER = 3;</code>
   */
  public static final int PAPER_NEWSPAPER_VALUE = 3;
  /**
   * <code>PAPER_BAG = 4;</code>
   */
  public static final int PAPER_BAG_VALUE = 4;
  /**
   * <code>GLASS_SODA_BOTTLE = 5;</code>
   */
  public static final int GLASS_SODA_BOTTLE_VALUE = 5;
  /**
   * <code>GLASS_JAR = 6;</code>
   */
  public static final int GLASS_JAR_VALUE = 6;
  /**
   * <code>GLASS_BOTTLE = 7;</code>
   */
  public static final int GLASS_BOTTLE_VALUE = 7;
  /**
   * <code>METAL_SMALL_CAN = 8;</code>
   */
  public static final int METAL_SMALL_CAN_VALUE = 8;
  /**
   * <code>METAL_CAN = 9;</code>
   */
  public static final int METAL_CAN_VALUE = 9;
  /**
   * <code>METAL_SODA_CAN = 10;</code>
   */
  public static final int METAL_SODA_CAN_VALUE = 10;
  /**
   * <code>POLYSTYRENE_CUP = 11;</code>
   */
  public static final int POLYSTYRENE_CUP_VALUE = 11;
  /**
   * <code>PIZZA_BOX = 12;</code>
   */
  public static final int PIZZA_BOX_VALUE = 12;
  /**
   * <code>MUG = 13;</code>
   */
  public static final int MUG_VALUE = 13;
  /**
   * <code>AEROSOL_CAN = 14;</code>
   */
  public static final int AEROSOL_CAN_VALUE = 14;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static WasteType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static WasteType forNumber(int value) {
    switch (value) {
      case 0: return PLASTIC_BOTTLE;
      case 1: return PLASTIC_JUG;
      case 2: return PLASTIC_DETERGENT_BOTTLE;
      case 3: return PAPER_NEWSPAPER;
      case 4: return PAPER_BAG;
      case 5: return GLASS_SODA_BOTTLE;
      case 6: return GLASS_JAR;
      case 7: return GLASS_BOTTLE;
      case 8: return METAL_SMALL_CAN;
      case 9: return METAL_CAN;
      case 10: return METAL_SODA_CAN;
      case 11: return POLYSTYRENE_CUP;
      case 12: return PIZZA_BOX;
      case 13: return MUG;
      case 14: return AEROSOL_CAN;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<WasteType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      WasteType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<WasteType>() {
          public WasteType findValueByNumber(int number) {
            return WasteType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.github.eco_heroes.proto.game_events.GameEventsProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final WasteType[] VALUES = values();

  public static WasteType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private WasteType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ecoheroes.WasteType)
}

