// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: game-events.proto
// Protobuf Java Version: 4.28.3

package com.github.eco_heroes.proto.game_events;

public interface WasteGeneratedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ecoheroes.WasteGenerated)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ecoheroes.WasteType waste = 1;</code>
   * @return The enum numeric value on the wire for waste.
   */
  int getWasteValue();
  /**
   * <code>.ecoheroes.WasteType waste = 1;</code>
   * @return The waste.
   */
  com.github.eco_heroes.proto.game_events.WasteType getWaste();
}
