// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: game-events.proto
// Protobuf Java Version: 4.28.3

package com.github.eco_heroes.proto.game_events;

/**
 * Protobuf type {@code ecoheroes.WasteGenerated}
 */
public final class WasteGenerated extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ecoheroes.WasteGenerated)
    WasteGeneratedOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      WasteGenerated.class.getName());
  }
  // Use WasteGenerated.newBuilder() to construct.
  private WasteGenerated(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private WasteGenerated() {
    waste_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.eco_heroes.proto.game_events.GameEventsProto.internal_static_ecoheroes_WasteGenerated_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.eco_heroes.proto.game_events.GameEventsProto.internal_static_ecoheroes_WasteGenerated_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.eco_heroes.proto.game_events.WasteGenerated.class, com.github.eco_heroes.proto.game_events.WasteGenerated.Builder.class);
  }

  public static final int WASTE_FIELD_NUMBER = 1;
  private int waste_ = 0;
  /**
   * <code>.ecoheroes.WasteType waste = 1;</code>
   * @return The enum numeric value on the wire for waste.
   */
  @java.lang.Override public int getWasteValue() {
    return waste_;
  }
  /**
   * <code>.ecoheroes.WasteType waste = 1;</code>
   * @return The waste.
   */
  @java.lang.Override public com.github.eco_heroes.proto.game_events.WasteType getWaste() {
    com.github.eco_heroes.proto.game_events.WasteType result = com.github.eco_heroes.proto.game_events.WasteType.forNumber(waste_);
    return result == null ? com.github.eco_heroes.proto.game_events.WasteType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (waste_ != com.github.eco_heroes.proto.game_events.WasteType.PLASTIC_BOTTLE.getNumber()) {
      output.writeEnum(1, waste_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (waste_ != com.github.eco_heroes.proto.game_events.WasteType.PLASTIC_BOTTLE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, waste_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.eco_heroes.proto.game_events.WasteGenerated)) {
      return super.equals(obj);
    }
    com.github.eco_heroes.proto.game_events.WasteGenerated other = (com.github.eco_heroes.proto.game_events.WasteGenerated) obj;

    if (waste_ != other.waste_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WASTE_FIELD_NUMBER;
    hash = (53 * hash) + waste_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.eco_heroes.proto.game_events.WasteGenerated parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.eco_heroes.proto.game_events.WasteGenerated parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.eco_heroes.proto.game_events.WasteGenerated parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.eco_heroes.proto.game_events.WasteGenerated parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.eco_heroes.proto.game_events.WasteGenerated parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.eco_heroes.proto.game_events.WasteGenerated parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.eco_heroes.proto.game_events.WasteGenerated parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.eco_heroes.proto.game_events.WasteGenerated parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.github.eco_heroes.proto.game_events.WasteGenerated parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.github.eco_heroes.proto.game_events.WasteGenerated parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.eco_heroes.proto.game_events.WasteGenerated parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.eco_heroes.proto.game_events.WasteGenerated parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.eco_heroes.proto.game_events.WasteGenerated prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ecoheroes.WasteGenerated}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ecoheroes.WasteGenerated)
      com.github.eco_heroes.proto.game_events.WasteGeneratedOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.eco_heroes.proto.game_events.GameEventsProto.internal_static_ecoheroes_WasteGenerated_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.eco_heroes.proto.game_events.GameEventsProto.internal_static_ecoheroes_WasteGenerated_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.eco_heroes.proto.game_events.WasteGenerated.class, com.github.eco_heroes.proto.game_events.WasteGenerated.Builder.class);
    }

    // Construct using com.github.eco_heroes.proto.game_events.WasteGenerated.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      waste_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.eco_heroes.proto.game_events.GameEventsProto.internal_static_ecoheroes_WasteGenerated_descriptor;
    }

    @java.lang.Override
    public com.github.eco_heroes.proto.game_events.WasteGenerated getDefaultInstanceForType() {
      return com.github.eco_heroes.proto.game_events.WasteGenerated.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.eco_heroes.proto.game_events.WasteGenerated build() {
      com.github.eco_heroes.proto.game_events.WasteGenerated result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.eco_heroes.proto.game_events.WasteGenerated buildPartial() {
      com.github.eco_heroes.proto.game_events.WasteGenerated result = new com.github.eco_heroes.proto.game_events.WasteGenerated(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.github.eco_heroes.proto.game_events.WasteGenerated result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.waste_ = waste_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.eco_heroes.proto.game_events.WasteGenerated) {
        return mergeFrom((com.github.eco_heroes.proto.game_events.WasteGenerated)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.eco_heroes.proto.game_events.WasteGenerated other) {
      if (other == com.github.eco_heroes.proto.game_events.WasteGenerated.getDefaultInstance()) return this;
      if (other.waste_ != 0) {
        setWasteValue(other.getWasteValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              waste_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int waste_ = 0;
    /**
     * <code>.ecoheroes.WasteType waste = 1;</code>
     * @return The enum numeric value on the wire for waste.
     */
    @java.lang.Override public int getWasteValue() {
      return waste_;
    }
    /**
     * <code>.ecoheroes.WasteType waste = 1;</code>
     * @param value The enum numeric value on the wire for waste to set.
     * @return This builder for chaining.
     */
    public Builder setWasteValue(int value) {
      waste_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.ecoheroes.WasteType waste = 1;</code>
     * @return The waste.
     */
    @java.lang.Override
    public com.github.eco_heroes.proto.game_events.WasteType getWaste() {
      com.github.eco_heroes.proto.game_events.WasteType result = com.github.eco_heroes.proto.game_events.WasteType.forNumber(waste_);
      return result == null ? com.github.eco_heroes.proto.game_events.WasteType.UNRECOGNIZED : result;
    }
    /**
     * <code>.ecoheroes.WasteType waste = 1;</code>
     * @param value The waste to set.
     * @return This builder for chaining.
     */
    public Builder setWaste(com.github.eco_heroes.proto.game_events.WasteType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      waste_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ecoheroes.WasteType waste = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearWaste() {
      bitField0_ = (bitField0_ & ~0x00000001);
      waste_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ecoheroes.WasteGenerated)
  }

  // @@protoc_insertion_point(class_scope:ecoheroes.WasteGenerated)
  private static final com.github.eco_heroes.proto.game_events.WasteGenerated DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.eco_heroes.proto.game_events.WasteGenerated();
  }

  public static com.github.eco_heroes.proto.game_events.WasteGenerated getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WasteGenerated>
      PARSER = new com.google.protobuf.AbstractParser<WasteGenerated>() {
    @java.lang.Override
    public WasteGenerated parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<WasteGenerated> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WasteGenerated> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.eco_heroes.proto.game_events.WasteGenerated getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

